// Generated by scripts/update-rosetta-q-corpus.mjs from Rosetta Code Category:Q.
// Do not edit entries manually; refresh the corpus with the script above.

export interface RosettaQExample {
  task: string;
  url: string;
  block: number;
  realQParse: boolean;
  source: string;
}

export const ROSETTA_Q_CORPUS: RosettaQExample[] = [
  {
    "task": "100 doors",
    "url": "https://rosettacode.org/wiki/100_doors#q",
    "block": 1,
    "source": "`closed`open(100#0b){@[x;where y;not]}/100#'(til[100]#'0b),'1b",
    "realQParse": true
  },
  {
    "task": "100 doors",
    "url": "https://rosettacode.org/wiki/100_doors#q",
    "block": 2,
    "source": "`closed`open (1+til 100) in {x*x} 1+til 10",
    "realQParse": true
  },
  {
    "task": "100 doors",
    "url": "https://rosettacode.org/wiki/100_doors#q",
    "block": 3,
    "source": "@[100#`closed; -1+{x*x}1+til 10; :; `open]",
    "realQParse": true
  },
  {
    "task": "99 bottles of beer",
    "url": "https://rosettacode.org/wiki/99_bottles_of_beer#q",
    "block": 1,
    "source": "bobw:{[n] {x,\" bottles of beer on the wall\\n\",x,\" bottles of beer\\nTake one down, pass it around\\n\",y,\" bottles of beer on the wall\\n\\n\"} . string (n;n-1)}\n-1 bobw each reverse 1 + til 99",
    "realQParse": true
  },
  {
    "task": "ABC problem",
    "url": "https://rosettacode.org/wiki/ABC_problem#q",
    "block": 1,
    "source": "BLOCKS:string`BO`XK`DQ`CP`NA`GT`RE`TG`QD`FS`JW`HU`VI`AN`OB`ER`FS`LY`PC`ZM\nWORDS:string`A`BARK`BOOK`TREAT`COMMON`SQUAD`CONFUSE\n\ncmw:{[s;b]                                                   / [str;blocks]\n  $[0=count s; 1b;                                           /   empty string\n    not any found:any each b=s 0; 0b;                        /   cannot proceed\n    any(1_s).z.s/:b(til count b)except/:where found] }",
    "realQParse": true
  },
  {
    "task": "ABC problem",
    "url": "https://rosettacode.org/wiki/ABC_problem#q",
    "block": 2,
    "source": "WORDS cmw\\:BLOCKS\n1101011b",
    "realQParse": true
  },
  {
    "task": "ABC problem",
    "url": "https://rosettacode.org/wiki/ABC_problem#q",
    "block": 3,
    "source": "Words:string`A`bark`BOOK`Treat`COMMON`squad`CONFUSE\ncmwi:{(`$x), `false`true cmw . upper each(x;y) }",
    "realQParse": true
  },
  {
    "task": "ABC problem",
    "url": "https://rosettacode.org/wiki/ABC_problem#q",
    "block": 4,
    "source": "Words cmwi\\:BLOCKS\nA       true\nbark    true\nBOOK    false\nTreat   true\nCOMMON  false\nsquad   true\nCONFUSE true",
    "realQParse": true
  },
  {
    "task": "Abundant odd numbers",
    "url": "https://rosettacode.org/wiki/Abundant_odd_numbers#q",
    "block": 1,
    "source": "s:{c where 0=x mod c:1+til x div 2}            / proper divisors\nsd:sum s@                                      / sum of proper divisors\nabundant:{x<sd x}\nFilter:{y where x each y}",
    "realQParse": true
  },
  {
    "task": "Abundant odd numbers",
    "url": "https://rosettacode.org/wiki/Abundant_odd_numbers#q",
    "block": 2,
    "source": "count A:Filter[abundant] 1+2*til 260000      / a batch of abundant odd numbers; 1000+ is enough\n1054\n\n1 sd'\\25#A                                   / first 25 abundant odd numbers, and the sum of their divisors\n945 1575 2205 2835 3465 4095 4725 5355 5775 5985 6435 6615 6825 7245 7425 7875 8085 8415 8505 8925 9135 9555 9765  10395 11025\n975 1649 2241 2973 4023 4641 5195 5877 6129 6495 6669 7065 7063 7731 7455 8349 8331 8433 8967 8931 9585 9597 10203 12645 11946\n\n1 sd\\A 999                                   / 1000th abundant odd number and the sum of its divisors\n492975 519361\n\n1 sd\\(not abundant@)(2+)/1000000000-1        / first abundant odd number above 1,000,000,000 and its divisors\n1000000575 1083561009",
    "realQParse": true
  },
  {
    "task": "Align columns",
    "url": "https://rosettacode.org/wiki/Align_columns#q",
    "block": 1,
    "source": "text:(\n  \"Given$a$text$file$of$many$lines,$where$fields$within$a$line$\";\n  \"are$delineated$by$a$single$'dollar'$character,$write$a$program\";\n  \"that$aligns$each$column$of$fields$by$ensuring$that$words$in$each$\";\n  \"column$are$separated$by$at$least$one$space.\";\n  \"Further,$allow$for$each$word$in$a$column$to$be$either$left$\";\n  \"justified,$right$justified,$or$center$justified$within$its$column.\" )\n\nta:{[aln;txt]                                                  / tabulate aligned\n  sl:(count'')s:\"$\"vs/:txt;                                    /   strings and their lengths\n  cw:{rl#\\:max x@/:\\:til max rl:count each x}sl;               /   cell widths\n  ps:$[aln=`R;-1-cw;1+cw]$''s;                                 /   padded strings\n  ps:$[aln=`C;(neg(cw-sl)div 2)rotate''ps;ps];                 /   center\n  1,[;\"\\n\\n\"]\"\\n\"sv raze each ps; }                            /   print",
    "realQParse": true
  },
  {
    "task": "Array concatenation",
    "url": "https://rosettacode.org/wiki/Array_concatenation#q",
    "block": 1,
    "source": "list1:1 2 3\nlist2:4 5 6\nlist1,list2",
    "realQParse": true
  },
  {
    "task": "Averages/Arithmetic mean",
    "url": "https://rosettacode.org/wiki/Averages%2FArithmetic_mean#q",
    "block": 1,
    "source": "mean:{(sum x)%count x}",
    "realQParse": true
  },
  {
    "task": "Averages/Mode",
    "url": "https://rosettacode.org/wiki/Averages%2FMode#q",
    "block": 1,
    "source": "mode:{(key x) where value x=max x} count each group @",
    "realQParse": true
  },
  {
    "task": "Cholesky decomposition",
    "url": "https://rosettacode.org/wiki/Cholesky_decomposition#q",
    "block": 1,
    "source": "solve:{[A;B] $[0h>type A;B%A;inv[A] mmu B]}\nak:{[m;k] (),/:m[;k]til k:k-1}\nakk:{[m;k] m[k;k:k-1]}\ntranspose:{$[0h=type x;flip x;enlist each x]}\nmult:{[A;B]$[0h=type A;A mmu B;A*B]}\t\t\ncholesky:{[A]\n\t{[A;L;n]\n\t\tl_k:solve[L;ak[A;n]];\n\t\tl_kk:first over sqrt[akk[A;n] - mult[transpose l_k;l_k]];\n\t\t({$[0h<type x;enlist x;x]}L,'0f),enlist raze transpose[l_k],l_kk\n\t\t}[A]/[sqrt A[0;0];1_1+til count first A]\n\t}\n\nshow cholesky (25 15 -5f;15 18 0f;-5 0 11f)\n-1\"\";\nshow cholesky (18 22 54 42f;22 70 86 62f;54 86 174 134f;42 62 134 106f)",
    "realQParse": true
  },
  {
    "task": "CSV data manipulation",
    "url": "https://rosettacode.org/wiki/CSV_data_manipulation#q",
    "block": 1,
    "source": "t:(\"IIIII\";enlist \",\")0: `:input.csv    / Read CSV file input.csv into table t\nt:update SUM:sum value flip t from t    / Add SUM column to t\n`:output.csv 0: csv 0: t                / Write updated table as CSV to output.csv",
    "realQParse": true
  },
  {
    "task": "Death Star",
    "url": "https://rosettacode.org/wiki/Death_Star#q",
    "block": 1,
    "source": "/ https://en.wikipedia.org/wiki/BMP_file_format\n/ BITMAPINFOHEADER / RGB24\n\n/ generate a header\n\ngenheader:{[w;h]\n   0x424d, \"x\"$(f2i4[54+4*h*w],0,0,0,0,54,0,0,0,40,0,0,0,\n                f2i4[h],f2i4[w],1,0,24,0,0,0,0,0,\n                f2i4[h*((w*3)+((w*3)mod 4))],\n                19,11,0,0,19,11,0,0,0,0,0,0,0,0,0,0)};\n\n/ generate a raster line at a vertical position\n\ngenrow:{[w;y;fcn]\n    row:enlist 0i;xx:0i;do[w;row,:fcn[xx;y];xx+:1i];row,:((w mod 4)#0i);1_row};\n\n/ generate a bitmap\n\ngenbitmap:{[w;h;fcn]\n    ary:enlist 0i;yy:0i;do[h;ary,:genrow[w;yy;fcn];yy+:1i];\"x\"$1_ary};\n\n/ deal with endianness\n/ might need to reverse last line if host computer is not a PC\n\nf2i4:{[x] r:x;\n  s0:r mod 256;r-:s0; r%:256;\n  s1:r mod 256;r-:s1; r%:256;\n  s2:r mod 256;r-:s2; r%:256;\n  s3:r mod 256;\n  \"h\"$(s0,s1,s2,s3)}\n\n/ compose and write a file\n\nwritebmp:{[w;h;fcn;fn] \n    fn 1: (genheader[h;w],genbitmap[w;h;fcn])};\n\n/ / usage example:\n/ w:400;\n/ h:300;\n/ fcn:{x0:x-w%2;y0:y-h%2;r:175;$[(r*r)>((x0*x0)+(y0*y0));(0;0;255);(0;255;0)]};\n/ fn:`:demo.bmp;\n/ writebmp[w;h;fcn;fn];",
    "realQParse": true
  },
  {
    "task": "Death Star",
    "url": "https://rosettacode.org/wiki/Death_Star#q",
    "block": 2,
    "source": "w:400; h:300; r:150; l:-0.5 0.7 0.5\nsqrt0:{$[x>0;sqrt x;0]};\n\n/ get x,y,z position of point on sphere given x,y,r\n\nz:{[x;y;r]sqrt0((r*r)-((x*x)+(y*y)))};\n\n/ get diffused light at point on sphere\n\nis:{[x;y;r]\n   z0:z[x;y;r];\n   s:(x;y;z0)%r;\n   $[z0>0;i:0.5*1+(+/)(s*l);i:0];\n   i};\n\n/ get pixel value at given image position\n\nfcn:{[xpx;ypx]\n   x:xpx-w%2;\n   y:ypx-h%2;\n   z1:z[x;y;r];\n   x2:x+190;\n   z2:170-z[x2;y;r];\n   $[(r*r)<((x*x)+(y*y));\n      $[y>-50;\n          i:3#0;\n          i:200 100 50];\n      $[z2>z1;\n         i:3#is[x;y;r]*140;\n         i:3#is[(-1*x2);(-1*y);r]*120]\n   ];\n   \"i\"$i};\n\n/ do it ...\n\n\\l bmp.q\nfn:`:demo.bmp;\nwritebmp[w;h;fcn;fn];",
    "realQParse": false
  },
  {
    "task": "Detect division by zero",
    "url": "https://rosettacode.org/wiki/Detect_division_by_zero#q",
    "block": 1,
    "source": "r:x%0\n?[1=sum r=(0n;0w;-0w);\"division by zero detected\";()]",
    "realQParse": true
  },
  {
    "task": "Euler method",
    "url": "https://rosettacode.org/wiki/Euler_method#q",
    "block": 1,
    "source": "t:0\ntime:100\nk:-0.07\ntr:20\nsol:()\nsteps:10\nh:time%steps\ntn:100\nwhile [t<time;tn1:tn + h*(k)*(tn-tr);sol:sol,tn1;tn:tn1;t:t+h]\nsol",
    "realQParse": true
  },
  {
    "task": "Factorial",
    "url": "https://rosettacode.org/wiki/Factorial#q",
    "block": 1,
    "source": "f:(*/)1+til@",
    "realQParse": true
  },
  {
    "task": "Factorial",
    "url": "https://rosettacode.org/wiki/Factorial#q",
    "block": 2,
    "source": "f:(*)over 1+til@",
    "realQParse": true
  },
  {
    "task": "Factorial",
    "url": "https://rosettacode.org/wiki/Factorial#q",
    "block": 3,
    "source": "f:prd 1+til@",
    "realQParse": true
  },
  {
    "task": "Factorial",
    "url": "https://rosettacode.org/wiki/Factorial#q",
    "block": 4,
    "source": "f:{(*/)1+til x}",
    "realQParse": true
  },
  {
    "task": "Factorial",
    "url": "https://rosettacode.org/wiki/Factorial#q",
    "block": 5,
    "source": "f:{$[x=1;1;x*.z.s x-1]}",
    "realQParse": true
  },
  {
    "task": "Filter",
    "url": "https://rosettacode.org/wiki/Filter#q",
    "block": 1,
    "source": "x where 0=x mod 2",
    "realQParse": true
  },
  {
    "task": "FizzBuzz",
    "url": "https://rosettacode.org/wiki/FizzBuzz#q",
    "block": 1,
    "source": "{(`$string x)^`fizzbuzz`buzz`fizz`(x mod\\:15 5 3)?'0}",
    "realQParse": true
  },
  {
    "task": "FizzBuzz",
    "url": "https://rosettacode.org/wiki/FizzBuzz#q",
    "block": 2,
    "source": "/ Fizzbuzz\nfb:{(`$string x)^`fizzbuzz`buzz`fizz`(x mod\\:15 5 3)?'0}\nfb 1+til 20\n`1`2`fizz`4`buzz`fizz`7`8`fizz`buzz`11`fizz`13`14`fizzbuzz`16`17`fizz`19`buzz",
    "realQParse": true
  },
  {
    "task": "FizzBuzz",
    "url": "https://rosettacode.org/wiki/FizzBuzz#q",
    "block": 3,
    "source": "show x:1+til 20\n1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20\nx mod\\:15 5 3\n1  1 1\n2  2 2\n3  3 0\n4  4 1\n5  0 2\n6  1 0\n..\n(x mod\\:15 5 3)?'0\n3 3 2 3 1 2 3 3 2 1 3 2 3 3 0 3 3 2 3 1\n`fizzbuzz`buzz`fizz`(x mod\\:15 5 3)?'0  / substitutions\n```fizz``buzz`fizz```fizz`buzz``fizz```fizzbuzz```fizz``buzz\n`$string x  / numbers => symbols\n`1`2`3`4`5`6`7`8`9`10`11`12`13`14`15`16`17`18`19`20\n(`$string x)^`fizzbuzz`buzz`fizz`(x mod\\:15 5 3)?'0  / replace nulls with numbers\n`1`2`fizz`4`buzz`fizz`7`8`fizz`buzz`11`fizz`13`14`fizzbuzz`16`17`fizz`19`buzz",
    "realQParse": false
  },
  {
    "task": "Flatten a list",
    "url": "https://rosettacode.org/wiki/Flatten_a_list#q",
    "block": 1,
    "source": "(raze/) ((1); 2; ((3;4); 5); ((())); (((6))); 7; 8; ())",
    "realQParse": true
  },
  {
    "task": "Floyd's triangle",
    "url": "https://rosettacode.org/wiki/Floyd's_triangle#q",
    "block": 1,
    "source": "floyd:{n:1+ til sum 1+til x;\n       t:d:0;\n       while[1+x-:1;0N!(t+:1)#(d+:t)_n]}\n\nfloyd2:{n:1+ til sum 1+til x;\n        t:d:0;\n        while[1+x-:1;1 (\" \" sv string each (t+:1)#(d+:t)_n),\"\\n\"]}\n\n//The latter function 'floyd2' includes logic to remove the leading \",\" before \"1\" in the first row.\n   \nfloyd[5]\nfloyd2[14]",
    "realQParse": true
  },
  {
    "task": "Four is magic",
    "url": "https://rosettacode.org/wiki/Four_is_magic#q",
    "block": 1,
    "source": "C:``one`two`three`four`five`six`seven`eight`nine`ten,\n  `eleven`twelve`thirteen`fourteen`fifteen`sixteen`seventeen`eighteen`nineteen                             / cardinal numbers <20\n\nT:``ten`twenty`thirty`forty`fifty`sixty`seventy`eighty`ninety                                              / tens\nM:``thousand`million`billion`trillion`quadrillion`quintillion`sextillion`septillion                        / magnitudes\n\nst:{                                                                                                       / stringify <1000\n  $[x<20; C x;\n    x<100; (T;C)@'10 vs x;\n    {C[y],`hundred,$[z=0;`;x z]}[.z.s] . 100 vs x] } \n\ns:{$[x=0; \"zero\"; {\" \"sv string except[;`]raze x{$[x~`;x;x,y]}'M reverse til count x} st each 1000 vs x]}  / stringify\n\nfim:{@[;0;upper],[;\"four is magic.\\n\"] raze 1_{y,\" is \",x,\", \"}prior s each(count s@)\\[x]}                 / four is magic\n\n1 raze fim each 0 4 8 16 25 89 365 2586 25865 369854 40000000001;                                          / tests",
    "realQParse": true
  },
  {
    "task": "Four is magic",
    "url": "https://rosettacode.org/wiki/Four_is_magic#q",
    "block": 2,
    "source": "show sl:count each string C  / string lengths\n0 3 3 5 4 4 3 5 5 4 3 6 6 8 8 7 7 9 8 8\nsl\\[18]\n18 8 5 4\nsl\\[19]\n19 8 5 4",
    "realQParse": true
  },
  {
    "task": "Function definition",
    "url": "https://rosettacode.org/wiki/Function_definition#q",
    "block": 1,
    "source": "multiply:{[a;b] a*b}",
    "realQParse": true
  },
  {
    "task": "Function definition",
    "url": "https://rosettacode.org/wiki/Function_definition#q",
    "block": 2,
    "source": "multiply:{x*y}",
    "realQParse": true
  },
  {
    "task": "Function definition",
    "url": "https://rosettacode.org/wiki/Function_definition#q",
    "block": 3,
    "source": "multiply:*",
    "realQParse": true
  },
  {
    "task": "Function definition",
    "url": "https://rosettacode.org/wiki/Function_definition#q",
    "block": 4,
    "source": "multiply[2;3]\n 6",
    "realQParse": true
  },
  {
    "task": "Greatest element of a list",
    "url": "https://rosettacode.org/wiki/Greatest_element_of_a_list#q",
    "block": 1,
    "source": "l:2 9 3 8 4 7\nmax l\n9",
    "realQParse": true
  },
  {
    "task": "Higher-order functions",
    "url": "https://rosettacode.org/wiki/Higher-order_functions#q",
    "block": 1,
    "source": "sayHi:{-1\"Hello \",x;}\ncallFuncWithParam:{x[\"Peter\"]}\ncallFuncWithParam sayHi\nHello Peter\ncallFuncWithParam[sayHi]\nHello Peter",
    "realQParse": true
  },
  {
    "task": "Integer sequence",
    "url": "https://rosettacode.org/wiki/Integer_sequence#q",
    "block": 1,
    "source": "({-1 string x; x+1}\\) 1",
    "realQParse": true
  },
  {
    "task": "Integer sequence",
    "url": "https://rosettacode.org/wiki/Integer_sequence#q",
    "block": 2,
    "source": "i:0; while[1;-1 string (i+:1)]",
    "realQParse": true
  },
  {
    "task": "Leap year",
    "url": "https://rosettacode.org/wiki/Leap_year#q",
    "block": 1,
    "source": "ly:{((0<>x mod 100) | 0=x mod 400) & 0=x mod 4}    / Return 1b if x is a leap year; 0b otherwise",
    "realQParse": true
  },
  {
    "task": "Look-and-say sequence",
    "url": "https://rosettacode.org/wiki/Look-and-say_sequence#q",
    "block": 1,
    "source": "las:{{raze string[count@'x],'@'[;0]x:where[differ x]_x}\\[x;1#\"1\"]}\nlas 8",
    "realQParse": true
  },
  {
    "task": "Luhn test of credit card numbers",
    "url": "https://rosettacode.org/wiki/Luhn_test_of_credit_card_numbers#q",
    "block": 1,
    "source": "sd:{s:0; while[x<>0; s+:x mod 10; x:floor x%10]; s}    / Sum digits of x\nluhn:{\n    r:reverse string x;                             / Reversed credit card number\n    o:(\"I\"$) each r[2*til ceiling (count r) % 2];   / Odd-indexed numbers\n    e:(\"I\"$) each r[1+2*til floor (count r) % 2];   / Even-indexed numbers\n    0=(sum o,sd each e*2) mod 10                    / Return 1b if checksum ends in 0; 0b otherwise\n}",
    "realQParse": true
  },
  {
    "task": "Mandelbrot set",
    "url": "https://rosettacode.org/wiki/Mandelbrot_set#q",
    "block": 1,
    "source": "/adapted from https://www.linkedin.com/pulse/want-work-k-1010data-michal-wallace\ns:{(.[-]x*x),2*prd x}            / complex square (x is R,Im pair)\nm:{floor sqrt sum x*x}           / magnitude (distance from origin)\nd: 120 60                        / dimensions of the picture\nt: -88 -30                       / camera translation\nf: reciprocal 40 20              / scale factor\n\nc: (,/:\\:) . f * t + til each d  / complex plane near mandelbrot set\nz: d # enlist 0 0                / 3d array of zeroes in same shape\nmb: c+ (s'')@\t\t\t\t\t   / mandelbrot: s(z) + c\nr: 1 _ 8 mb\\z                    / collect 8 times\n\no: \" 12345678\"@ sum 2<m'''[r]    / \"color\" by how soon point \"escapes\"\n\n-1 \"\\n\"sv flip o;                / transpose and print the output",
    "realQParse": true
  },
  {
    "task": "Operator precedence",
    "url": "https://rosettacode.org/wiki/Operator_precedence#q",
    "block": 1,
    "source": "3*2+1\n9\n(3*2)+1    / Brackets give the usual order of precedence\n7\nx:5\n(x+5; x:20; x-5)\n25 20 0",
    "realQParse": true
  },
  {
    "task": "Pascal's triangle",
    "url": "https://rosettacode.org/wiki/Pascal's_triangle#q",
    "block": 1,
    "source": "pascal:{(x-1){0+':x,0}\\1}\npascal 5\n1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1",
    "realQParse": true
  },
  {
    "task": "Read entire file",
    "url": "https://rosettacode.org/wiki/Read_entire_file#q",
    "block": 1,
    "source": "file:read0`:file.txt\n\"First line of file\"\n\"Second line of file\"\n\"\"",
    "realQParse": true
  },
  {
    "task": "SEDOLs",
    "url": "https://rosettacode.org/wiki/SEDOLs#q",
    "block": 1,
    "source": "scd:{\n    v:{(\"i\"$x) - ?[(\"0\"<=x) & x<=\"9\"; \"i\"$\"0\"; -10+\"i\"$\"A\"]} each x; / Turn characters of SEDOL into their values\n    w:sum v*1 3 1 7 3 9;        / Weighted sum of values\n    d:(10 - w mod 10) mod 10;   / Check digit value\n    x,\"c\"$((\"i\"$\"0\")+d)         / Append to SEDOL\n}\n\nscd each (\"710889\";\"B0YBKJ\";\"406566\";\"B0YBLH\";\"228276\";\"B0YBKL\";\"557910\";\"B0YBKR\";\"585284\";\"B0YBKT\";\"B00030\")",
    "realQParse": true
  },
  {
    "task": "Sum multiples of 3 and 5",
    "url": "https://rosettacode.org/wiki/Sum_multiples_of_3_and_5#q",
    "block": 1,
    "source": "s35:{sum {?[(0=x mod 3) | 0=x mod 5;x;0]} each 1+til x - 1}\ns35 each 10 100 1000 10000 1000000",
    "realQParse": true
  },
  {
    "task": "Sum multiples of 3 and 5",
    "url": "https://rosettacode.org/wiki/Sum_multiples_of_3_and_5#q",
    "block": 2,
    "source": "sn:{x*(x+1)%2}      / Sum of 1 to n\ns35:{a:x-1; (3*sn floor a%3) + (5*sn floor a%5) - (15*sn floor a%15)}\ns35 e+10",
    "realQParse": true
  },
  {
    "task": "Sum of a series",
    "url": "https://rosettacode.org/wiki/Sum_of_a_series#q",
    "block": 1,
    "source": "sn:{sum xexp[;-2] 1+til x}\nsn 1000",
    "realQParse": true
  },
  {
    "task": "Sum of squares",
    "url": "https://rosettacode.org/wiki/Sum_of_squares#q",
    "block": 1,
    "source": "ssq:{sum x*x}",
    "realQParse": true
  },
  {
    "task": "Summarize and say sequence",
    "url": "https://rosettacode.org/wiki/Summarize_and_say_sequence#q",
    "block": 1,
    "source": "ls:{raze(string 1_ deltas d,count x),'x d:where differ x}  / look & say\nsumsay:ls desc@                                            / summarize & say\n\nseeds:group desc each string til 1000000                   / seeds for million integers\nseq:(key seeds)!30 sumsay\\'key seeds                       / sequences for unique seeds\ntop:max its:(count distinct@)each seq                      / count iterations\n\n/ report results\nrpt:{1 x,\": \",y,\"\\n\\n\";}\nrpt[\"Seeds\"]\" \"sv string raze seeds where its=top          / all forms of top seed/s\nrpt[\"Iterations\"]string top\nrpt[\"Sequence\"]\"\\n\\n\",\"\\n\"sv raze seq where its=top",
    "realQParse": true
  },
  {
    "task": "System time",
    "url": "https://rosettacode.org/wiki/System_time#q",
    "block": 1,
    "source": ".z.D\n2010.01.25\n.z.N\n0D14:17:45.519682000\n.z.P\n2010.01.25D14:17:46.962375000\n.z.T\n14:17:47.817\n.z.Z\n2010.01.25T14:17:48.711\n.z.z\n2010.01.25T19:17:59.445",
    "realQParse": true
  },
  {
    "task": "The Name Game",
    "url": "https://rosettacode.org/wiki/The_Name_Game#q",
    "block": 1,
    "source": "game_ssr:{[Name]\n  V:raze 1 lower\\\"AEIOUY\";                                        / vowels\n  tn:lower((Name in V)?1b) _ Name;                                / truncated Name\n  s3:{1(-1_)\\x,\"o-\",x}lower first Name;                           / 3rd ssr\n  s:\"$1, $1, bo-b$2\\nBanana-fana-fo-f$2\\nFee-fimo-m$2\\n$1!\\n\\n\";\n  (ssr/).(s;(\"$1\";\"$2\";s3 0);(Name;tn;s3 1)) }",
    "realQParse": true
  },
  {
    "task": "The Name Game",
    "url": "https://rosettacode.org/wiki/The_Name_Game#q",
    "block": 2,
    "source": "game_amend:{[Name]\n  pfx:Name,\", \",Name,\", \";                                    / prefix\n  n:lower Name;\n  sfx:((n in \"aeiouy\")?1b)_n;                                 / suffix\n  s:(\"bo-b\";\"Banana-fana fo-f\";\"Fee-fimo-m\";\"!\";\"\");          / song template\n  @[;0;pfx,] @[;3;Name,] @[;0 1 2;,[;sfx]] @[;where n[0]=last each s;-1_] s }\n\n// test\n1 \"\\n\"sv raze game_ssr each (\"Gary\";\"Earl\";\"Felix\";\"Stephen\";\"Ryan\";\"Jo\");",
    "realQParse": true
  },
  {
    "task": "The Twelve Days of Christmas",
    "url": "https://rosettacode.org/wiki/The_Twelve_Days_of_Christmas#q",
    "block": 1,
    "source": "DAYS:\" \"vs\"first second third fourth fifth sixth\",\n  \" seventh eighth ninth tenth eleventh twelfth\"\n\nSTANZA:(                              / final stanza\n  \"On the twelfth day of Christmas\";\n  \"My true love gave to me:\";\n  \"Twelve drummers drumming\";\n  \"Eleven pipers piping\";\n  \"Ten lords a-leaping\";\n  \"Nine ladies dancing\";\n  \"Eight maids a-milking\";\n  \"Seven swans a-swimming\";\n  \"Six geese a-laying\";\n  \"Five golden rings\";\n  \"Four calling birds\";\n  \"Three french hens\";\n  \"Two turtle doves\";\n  \"And a partridge in a pear tree.\";\n  \"\")\n\n-1 raze \n  .[;0 2;\"A\",5_]                         / tweak one line\n  .[;(::;0);ssr[;\"twelfth\";];DAYS]       / number the verses\n  STANZA 0 1,/:#\\:[;til 15] -2 -til 12;  / compose 12 verses",
    "realQParse": true
  },
  {
    "task": "Tokenize a string",
    "url": "https://rosettacode.org/wiki/Tokenize_a_string#q",
    "block": 1,
    "source": "words: \",\" vs \"Hello,How,Are,You,Today\"\n\".\" sv words",
    "realQParse": true
  },
  {
    "task": "Word wheel",
    "url": "https://rosettacode.org/wiki/Word_wheel#q",
    "block": 1,
    "source": "ce:count each\nlc:ce group@                                              / letter count\ndict:\"\\n\"vs .Q.hg \"http://wiki.puzzlers.org/pub/wordlists/unixdict.txt\"\n// dictionary of 3-9 letter words\nd39:{x where(ce x)within 3 9}{x where all each x in .Q.a}dict\n\nsolve:{[grid;dict]\n  i:where(grid 4)in'dict;\n  dict i where all each 0<=(lc grid)-/:lc each dict i }[;d39]",
    "realQParse": true
  },
  {
    "task": "Word wheel",
    "url": "https://rosettacode.org/wiki/Word_wheel#q",
    "block": 2,
    "source": "`$solve \"ndeokglew\"\n`eke`elk`keel`keen`keg`ken`keno`knee`kneel`knew`know`knowledge`kong`leek`week`wok`woke",
    "realQParse": true
  },
  {
    "task": "Word wheel",
    "url": "https://rosettacode.org/wiki/Word_wheel#q",
    "block": 3,
    "source": "bust:{[dict]\n  grids:distinct raze(til 9)rotate\\:/:dict where(ce dict)=9;\n  wc:(count solve@)each grids;\n  grids where wc=max wc }",
    "realQParse": true
  },
  {
    "task": "Word wheel",
    "url": "https://rosettacode.org/wiki/Word_wheel#q",
    "block": 4,
    "source": "best:{[dict]\n  dlc:lc each dict;                                      / letter counts of dictionary words\n  ig:where(ce dict)=9;                                   / find grids (9-letter words)\n  igw:where each(all'')0<=(dlc ig)-/:\\:dlc;              / find words composable from each grid (length ig)\n  grids:raze(til 9)rotate\\:/:dict ig;                    / 9 permutations of each grid\n  iaz:(.Q.a)!where each .Q.a in'\\:dict;                  / find words containing a, b, c etc\n  ml:4 rotate'dict ig;                                   / mid letters for each grid\n  wc:ce raze igw inter/:'iaz ml;                         / word counts for grids\n  distinct grids where wc=max wc }                       / grids with most words",
    "realQParse": true
  },
  {
    "task": "Word wheel",
    "url": "https://rosettacode.org/wiki/Word_wheel#q",
    "block": 5,
    "source": "show w:best d39\n\"ntclaremo\"\n\"tspearmin\"\n\nce solve each w\n215 215",
    "realQParse": true
  },
  {
    "task": "Y combinator",
    "url": "https://rosettacode.org/wiki/Y_combinator#q",
    "block": 1,
    "source": "Y: {{x x} {({y {(x x) y} x} y) x} x}\nfac: {{$[y<2; 1; y*x y-1]} x}\n(Y fac) 6\n720j\nfib: {{$[y<2; y;  (x y-1) + (x y-2)]} x}\n(Y fib) each til 20\n0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181",
    "realQParse": true
  }
];
