import { QANVAS_COLORS } from '$lib/runtime/compiled-runtime-helpers';


export const Q_KEYWORDS = [
  'select',
  'from',
  'where',
  'by',
  'update',
  'delete',
  'exec',
  'insert',
  'upsert',
  'each',
  'over',
  'scan',
  'prior',
  'flip',
  'enlist',
  'count',
  'first',
  'last',
  'avg',
  'sum',
  'min',
  'max',
  'all',
  'any',
  'not',
  'neg',
  'abs',
  'sqrt',
  'exp',
  'log',
  'sin',
  'cos',
  'tan',
  'string',
  'value',
  'key',
  'type',
  'null',
  'inf',
  'asc',
  'desc',
  'iasc',
  'idesc',
  'distinct',
  'group',
  'ungroup',
  'cols',
  'meta',
  'tables',
  'views',
  'load',
  'save',
  'get',
  'set',
  'til',
  'do',
  'while',
  'if',
  'and',
  'or',
  'like',
  'ss',
  'sv',
  'vs',
  'in',
  'within',
  'bin',
  'binr',
  'asof',
  'aj',
  'aj0',
  'lj',
  'lj0',
  'ij',
  'ij0',
  'pj',
  'uj',
  'wj',
  'wj1',
  'fby',
  'xasc',
  'xdesc',
  'xgroup',
  'xcols',
  'xcept',
  'inter',
  'union',
  'diff',
  'except',
];

export const Q_BUILTIN_FUNCTIONS = [
  'neg',
  'not',
  'null',
  'string',
  'reciprocal',
  'floor',
  'ceiling',
  'signum',
  'mod',
  'xbar',
  'xlog',
  'and',
  'or',
  'each',
  'scan',
  'over',
  'prior',
  'mmu',
  'lsq',
  'inv',
  'md5',
  'ltime',
  'gtime',
  'count',
  'first',
  'svar',
  'sdev',
  'scov',
  'med',
  'all',
  'any',
  'rand',
  'sums',
  'prds',
  'mins',
  'maxs',
  'fills',
  'deltas',
  'ratios',
  'avgs',
  'differ',
  'prev',
  'next',
  'rank',
  'reverse',
  'iasc',
  'idesc',
  'asc',
  'desc',
  'msum',
  'mcount',
  'mavg',
  'mdev',
  'xrank',
  'mmin',
  'mmax',
  'xprev',
  'rotate',
  'ema',
  'distinct',
  'group',
  'where',
  'flip',
  'type',
  'key',
  'til',
  'get',
  'value',
  'attr',
  'cut',
  'set',
  'upsert',
  'raze',
  'union',
  'inter',
  'except',
  'cross',
  'sv',
  'vs',
  'sublist',
  'read0',
  'read1',
  'hclose',
  'hdel',
  'hsym',
  'hcount',
  'peach',
  'system',
  'ltrim',
  'rtrim',
  'trim',
  'lower',
  'upper',
  'ssr',
  'view',
  'tables',
  'views',
  'cols',
  'xcols',
  'keys',
  'xkey',
  'xcol',
  'xasc',
  'xdesc',
  'fkeys',
  'meta',
  'lj',
  'ljf',
  'aj',
  'aj0',
  'ajf',
  'ajf0',
  'ij',
  'ijf',
  'pj',
  'asof',
  'uj',
  'ujf',
  'ww',
  'wj',
  'wj1',
  'fby',
  'xgroup',
  'ungroup',
  'ej',
  'save',
  'load',
  'rsave',
  'rload',
  'dsave',
  'show',
  'csv',
  'parse',
  'eval',
  'reval',
  'use',
];

export const Q_NAMESPACE_SYMBOLS = [
  { label: '.cx._usage', detail: 'complex helper', documentation: 'Usage notes for the built-in complex-number helper namespace.', type: 'variable' },
  { label: '.cx.abs', detail: 'complex helper', documentation: 'Magnitude of a complex value.', type: 'function' },
  { label: '.cx.add', detail: 'complex helper', documentation: 'Add two complex values.', type: 'function' },
  { label: '.cx.arg', detail: 'complex helper', documentation: 'Phase angle of a complex value.', type: 'function' },
  { label: '.cx.ceil', detail: 'complex helper', documentation: 'Ceiling of the real and imaginary parts.', type: 'function' },
  { label: '.cx.conj', detail: 'complex helper', documentation: 'Complex conjugate.', type: 'function' },
  { label: '.cx.cos', detail: 'complex helper', documentation: 'Complex cosine.', type: 'function' },
  { label: '.cx.div', detail: 'complex helper', documentation: 'Divide two complex values.', type: 'function' },
  { label: '.cx.exp', detail: 'complex helper', documentation: 'Complex exponential.', type: 'function' },
  { label: '.cx.floor', detail: 'complex helper', documentation: 'Floor of the real and imaginary parts.', type: 'function' },
  { label: '.cx.frac', detail: 'complex helper', documentation: 'Fractional part of a complex value.', type: 'function' },
  { label: '.cx.from', detail: 'complex helper', documentation: 'Coerce a q value into a complex value.', type: 'function' },
  { label: '.cx.fromPolar', detail: 'complex helper', documentation: 'Build a complex value from radius and angle.', type: 'function' },
  { label: '.cx.i', detail: 'complex constant', documentation: 'The imaginary unit.', type: 'constant' },
  { label: '.cx.im', detail: 'complex helper', documentation: 'Imaginary component of a complex value.', type: 'function' },
  { label: '.cx.log', detail: 'complex helper', documentation: 'Complex natural logarithm.', type: 'function' },
  { label: '.cx.mod', detail: 'complex helper', documentation: 'Complex modulo.', type: 'function' },
  { label: '.cx.modulus', detail: 'complex helper', documentation: 'Magnitude of a complex value.', type: 'function' },
  { label: '.cx.mul', detail: 'complex helper', documentation: 'Multiply two complex values.', type: 'function' },
  { label: '.cx.neg', detail: 'complex helper', documentation: 'Negate a complex value.', type: 'function' },
  { label: '.cx.new', detail: 'complex helper', documentation: 'Build a complex value from real and imaginary parts.', type: 'function' },
  { label: '.cx.normalize', detail: 'complex helper', documentation: 'Normalize a complex value to unit magnitude.', type: 'function' },
  { label: '.cx.one', detail: 'complex constant', documentation: 'Complex one.', type: 'constant' },
  { label: '.cx.polar', detail: 'complex helper', documentation: 'Return radius and angle for a complex value.', type: 'function' },
  { label: '.cx.pow', detail: 'complex helper', documentation: 'Raise a complex value to a power.', type: 'function' },
  { label: '.cx.powEach', detail: 'complex helper', documentation: 'Element-wise complex power helper.', type: 'function' },
  { label: '.cx.re', detail: 'complex helper', documentation: 'Real component of a complex value.', type: 'function' },
  { label: '.cx.recip', detail: 'complex helper', documentation: 'Reciprocal of a complex value.', type: 'function' },
  { label: '.cx.round', detail: 'complex helper', documentation: 'Round the real and imaginary parts.', type: 'function' },
  { label: '.cx.sin', detail: 'complex helper', documentation: 'Complex sine.', type: 'function' },
  { label: '.cx.sqrt', detail: 'complex helper', documentation: 'Complex square root.', type: 'function' },
  { label: '.cx.str', detail: 'complex helper', documentation: 'Format a complex value as text.', type: 'function' },
  { label: '.cx.sub', detail: 'complex helper', documentation: 'Subtract two complex values.', type: 'function' },
  { label: '.cx.tan', detail: 'complex helper', documentation: 'Complex tangent.', type: 'function' },
  { label: '.cx.z', detail: 'complex helper', documentation: 'Alias for .cx.new.', type: 'function' },
  { label: '.cx.zero', detail: 'complex constant', documentation: 'Complex zero.', type: 'constant' },
  { label: '.Q.A', detail: '.Q constant', documentation: 'Uppercase alphabet string.', type: 'constant' },
  { label: '.Q.K', detail: '.Q constant', documentation: 'Null date constant.', type: 'constant' },
  { label: '.Q.M', detail: '.Q constant', documentation: 'Maximum long/infinity helper.', type: 'constant' },
  { label: '.Q.a', detail: '.Q constant', documentation: 'Lowercase alphabet string.', type: 'constant' },
  { label: '.Q.addmonths', detail: '.Q built-in', documentation: 'Add months to date values.', type: 'function' },
  { label: '.Q.an', detail: '.Q constant', documentation: 'Alphanumeric identifier characters.', type: 'constant' },
  { label: '.Q.atob', detail: '.Q built-in', documentation: 'Decode base64 text.', type: 'function' },
  { label: '.Q.b6', detail: '.Q constant', documentation: 'Base64 alphabet string.', type: 'constant' },
  { label: '.Q.btoa', detail: '.Q built-in', documentation: 'Encode text as base64.', type: 'function' },
  { label: '.Q.cols', detail: '.Q constant', documentation: 'Current console column count.', type: 'constant' },
  { label: '.Q.def', detail: '.Q built-in', documentation: 'Apply defaults to parsed command-line options.', type: 'function' },
  { label: '.Q.f', detail: '.Q built-in', documentation: 'Format floating values with fixed decimals.', type: 'function' },
  { label: '.Q.fmt', detail: '.Q built-in', documentation: 'Format numbers with width and decimal precision.', type: 'function' },
  { label: '.Q.id', detail: '.Q built-in', documentation: 'Sanitize symbols, dictionaries, or table column names into valid q identifiers.', type: 'function' },
  { label: '.Q.j10', detail: '.Q built-in', documentation: 'Decode a base-10 fixed-width encoded string.', type: 'function' },
  { label: '.Q.j12', detail: '.Q built-in', documentation: 'Decode a base-12 fixed-width encoded string.', type: 'function' },
  { label: '.Q.k', detail: '.Q constant', documentation: 'q version number.', type: 'constant' },
  { label: '.Q.n', detail: '.Q constant', documentation: 'Digit string.', type: 'constant' },
  { label: '.Q.nA', detail: '.Q constant', documentation: 'Base-36 alphabet string.', type: 'constant' },
  { label: '.Q.opt', detail: '.Q built-in', documentation: 'Parse argv-style option values.', type: 'function' },
  { label: '.Q.res', detail: '.Q constant', documentation: 'Reserved q words as symbols.', type: 'constant' },
  { label: '.Q.rows', detail: '.Q constant', documentation: 'Current console row count.', type: 'constant' },
  { label: '.Q.s', detail: '.Q built-in', documentation: 'Render a value using q formatting.', type: 'function' },
  { label: '.Q.x10', detail: '.Q built-in', documentation: 'Encode a value with the base-10 fixed-width alphabet.', type: 'function' },
  { label: '.Q.x12', detail: '.Q built-in', documentation: 'Encode a value with the base-12 fixed-width alphabet.', type: 'function' },
  { label: '.z.D', detail: '.z value', documentation: 'Current date.', type: 'constant' },
  { label: '.z.K', detail: '.z value', documentation: 'q version number.', type: 'constant' },
  { label: '.z.P', detail: '.z value', documentation: 'Current timestamp.', type: 'constant' },
  { label: '.z.T', detail: '.z value', documentation: 'Current time.', type: 'constant' },
  { label: '.z.Z', detail: '.z value', documentation: 'Current timezone.', type: 'constant' },
  { label: '.z.e', detail: '.z value', documentation: 'Environment variables.', type: 'constant' },
  { label: '.z.o', detail: '.z value', documentation: 'Runtime/user-agent descriptor.', type: 'constant' },
  { label: '.z.x', detail: '.z value', documentation: 'Command-line arguments.', type: 'constant' },
] as const;

export const Q_CANVAS_FUNCTIONS = [
  {
    label: 'background',
    detail: 'Qanvas draw helper',
    documentation: 'Fills the canvas background for the current frame.',
    insertText: 'background[${1:Color.CREAM}];',
  },
  {
    label: 'circle',
    detail: 'Qanvas draw helper',
    documentation: 'Draws circles from a q table of positions, radii, and styles.',
    insertText: 'circle[${1:data}];',
  },
  {
    label: 'rect',
    detail: 'Qanvas draw helper',
    documentation: 'Draws rectangles from a q table of positions, sizes, and styles.',
    insertText: 'rect[${1:data}];',
  },
  {
    label: 'pixel',
    detail: 'Qanvas draw helper',
    documentation: 'Draws single-pixel fills from a q table of positions and styles.',
    insertText: 'pixel[${1:data}];',
  },
  {
    label: 'line',
    detail: 'Qanvas draw helper',
    documentation: 'Draws lines from a q table with p and p2 coordinates.',
    insertText: 'line[${1:data}];',
  },
  {
    label: 'text',
    detail: 'Qanvas draw helper',
    documentation: 'Draws text labels from a q table of positions and strings.',
    insertText: 'text[${1:data}];',
  },
  {
    label: 'image',
    detail: 'Qanvas draw helper',
    documentation: 'Draws images from a q table of source paths and positions.',
    insertText: 'image[${1:data}];',
  },
  {
    label: 'generic',
    detail: 'Qanvas draw helper',
    documentation: 'Pushes already-shaped draw commands directly into the render queue.',
    insertText: 'generic[${1:cmds}];',
  },
  {
    label: 'push',
    detail: 'Qanvas transform helper',
    documentation: 'Saves the current canvas transform state.',
    insertText: 'push[];',
  },
  {
    label: 'pop',
    detail: 'Qanvas transform helper',
    documentation: 'Restores the previous canvas transform state.',
    insertText: 'pop[];',
  },
  {
    label: 'translate',
    detail: 'Qanvas transform helper',
    documentation: 'Translates the drawing origin by x and y.',
    insertText: 'translate[${1:0 0}];',
  },
  {
    label: 'scale',
    detail: 'Qanvas transform helper',
    documentation: 'Scales the drawing space uniformly or per axis.',
    insertText: 'scale[${1:1}];',
  },
  {
    label: 'cursor',
    detail: 'Qanvas input helper',
    documentation: 'Sets the canvas cursor for the current frame.',
    insertText: 'cursor[${1:`crosshair}];',
  },
];

export const Q_CONTEXT_SYMBOLS = [
  {
    label: 'setup',
    detail: 'Sketch lifecycle',
    documentation: 'Runs once when the sketch starts and returns the initial config/state.',
    insertText: 'setup:{\n  `size`bg!(${1:800 600};${2:Color.CREAM})\n}',
  },
  {
    label: 'draw',
    detail: 'Sketch lifecycle',
    documentation: 'Runs every frame and must return the next state.',
    insertText:
      'draw:{[state;frameInfo;input;canvas]\n  ${1:background[Color.CREAM];}\n  ${2:state}\n}',
  },
  {
    label: 'state',
    detail: 'draw arg',
    documentation: 'The current sketch state that draw should evolve and return.',
    insertText: 'state',
  },
  {
    label: 'frameInfo',
    detail: 'draw arg',
    documentation: 'Per-frame timing data with frameNum, time, and dt.',
    insertText: 'frameInfo',
  },
  {
    label: 'input',
    detail: 'draw arg',
    documentation: 'Current mouse, keyboard, and scroll input for this frame.',
    insertText: 'input',
  },
  {
    label: 'canvas',
    detail: 'draw arg',
    documentation: 'Canvas metadata including size and pixelRatio.',
    insertText: 'canvas',
  },
  {
    label: 'frameInfo`frameNum',
    detail: 'frame field',
    documentation: 'The zero-based frame counter.',
    insertText: 'frameInfo`frameNum',
  },
  {
    label: 'frameInfo`time',
    detail: 'frame field',
    documentation: 'Elapsed time in milliseconds.',
    insertText: 'frameInfo`time',
  },
  {
    label: 'frameInfo`dt',
    detail: 'frame field',
    documentation: 'Delta time for the current frame.',
    insertText: 'frameInfo`dt',
  },
  {
    label: 'input`mouse',
    detail: 'input field',
    documentation: 'Mouse position as x y.',
    insertText: 'input`mouse',
  },
  {
    label: 'input`mouseButtons',
    detail: 'input field',
    documentation: 'Mouse button state for left, middle, and right.',
    insertText: 'input`mouseButtons',
  },
  {
    label: 'input`scroll',
    detail: 'input field',
    documentation: 'Current scroll delta.',
    insertText: 'input`scroll',
  },
  {
    label: 'input`key',
    detail: 'input field',
    documentation: 'Most recent key pressed.',
    insertText: 'input`key',
  },
  {
    label: 'input`keys',
    detail: 'input field',
    documentation: 'List of currently pressed keys.',
    insertText: 'input`keys',
  },
  {
    label: 'canvas`size',
    detail: 'canvas field',
    documentation: 'Canvas width and height.',
    insertText: 'canvas`size',
  },
  {
    label: 'canvas`pixelRatio',
    detail: 'canvas field',
    documentation: 'Device pixel ratio used by the renderer.',
    insertText: 'canvas`pixelRatio',
  },
];

export const Q_COLOR_SYMBOLS = Object.entries(QANVAS_COLORS).map(([name, value]) => ({
  label: `Color.${name}`,
  detail: 'Qanvas color',
  documentation: `Built-in color constant, equivalent to 0x${value.toString(16).toUpperCase().padStart(6, '0')}.`,
  insertText: `Color.${name}`,
}));

const Q_QANVAS_IDENTIFIERS = [
  ...Q_CANVAS_FUNCTIONS.map((item) => item.label),
  ...Q_COLOR_SYMBOLS.map((item) => item.label),
  ...Q_CONTEXT_SYMBOLS.map((item) => item.label).filter((label) => /^[a-zA-Z_][a-zA-Z0-9_.]*$/.test(label)),
];

const Q_KEYWORD_SET = new Set(Q_KEYWORDS.map((w) => w.toLowerCase()));
const Q_BUILTIN_SET = new Set([...Q_BUILTIN_FUNCTIONS, ...Q_NAMESPACE_SYMBOLS.map((item) => item.label)].map((w) => w.toLowerCase()));
const Q_QANVAS_SET = new Set(Q_QANVAS_IDENTIFIERS.map((w) => w.toLowerCase()));

/**
 * Classify a q identifier token the same way as the desktop Monarch grammar
 * (qanvas API / colors → builtins → keywords → default identifier).
 */
export function classifyMobileQIdent(raw: string): 'qanvas' | 'builtin' | 'keyword' | 'identifier' {
  if (!/^[a-zA-Z_.][a-zA-Z0-9_.]*$/.test(raw)) return 'identifier';
  const lower = raw.toLowerCase();
  const leaf = raw.includes('.') ? raw.slice(raw.lastIndexOf('.') + 1).toLowerCase() : lower;

  if (Q_QANVAS_SET.has(lower)) return 'qanvas';
  // Same order as desktop Monarch: builtins before keywords (many verbs appear in both lists).
  if (Q_BUILTIN_SET.has(lower) || Q_BUILTIN_SET.has(leaf)) return 'builtin';
  if (Q_KEYWORD_SET.has(lower) || Q_KEYWORD_SET.has(leaf)) return 'keyword';
  return 'identifier';
}

export const Q_SLASH_SNIPPETS = [
  {
    label: '/sketch',
    detail: 'Snippet',
    documentation: 'Creates a complete setup/draw sketch scaffold.',
    insertText:
      'setup:{\n  `size`bg!(${1:800 600};${2:Color.CREAM})\n}\n\ndraw:{[state;frameInfo;input;canvas]\n  background[${2:Color.CREAM}];\n  ${3:state}\n}\n',
  },
  {
    label: '/setup',
    detail: 'Snippet',
    documentation: 'Creates a setup function scaffold.',
    insertText: 'setup:{\n  `size`bg!(${1:800 600};${2:Color.CREAM})\n}',
  },
  {
    label: '/draw',
    detail: 'Snippet',
    documentation: 'Creates a draw function scaffold.',
    insertText:
      'draw:{[state;frameInfo;input;canvas]\n  ${1:background[Color.CREAM];}\n  ${2:state}\n}',
  },
  {
    label: '/function',
    detail: 'Snippet',
    documentation: 'Creates a niladic (zero-argument) function in q style: name:{[] …}.',
    insertText: '${1:fn}:{[]\n  ${2:1+1}\n}',
  },
  {
    label: '/function1',
    detail: 'Snippet',
    documentation: 'Creates a monadic (one-argument) function in q style: name:{[x] …}.',
    insertText: '${1:fn}:{[${2:x}]\n  ${3:x}\n}',
  },
  {
    label: '/function2',
    detail: 'Snippet',
    documentation: 'Creates a dyadic (two-argument) function in q style: name:{[x;y] …}.',
    insertText: '${1:fn}:{[${2:x};${3:y}]\n  ${4:x+y}\n}',
  },
  {
    label: '/function3',
    detail: 'Snippet',
    documentation: 'Creates a triadic (three-argument) function in q style: name:{[x;y;z] …}.',
    insertText: '${1:fn}:{[${2:x};${3:y};${4:z}]\n  ${5:x+y+z}\n}',
  },
  {
    label: '/background',
    detail: 'Snippet',
    documentation: 'Inserts a background command.',
    insertText: 'background[${1:Color.CREAM}];',
  },
  {
    label: '/circle',
    detail: 'Snippet',
    documentation: 'Inserts a circle command scaffold.',
    insertText:
      'circle[([]\n  p:enlist ${1:0.5*canvas`size};\n  r:enlist ${2:44};\n  fill:enlist ${3:Color.BLUE};\n  alpha:enlist ${4:0.92}\n)];',
  },
  {
    label: '/rect',
    detail: 'Snippet',
    documentation: 'Inserts a rectangle command scaffold.',
    insertText:
      'rect[([]\n  p:enlist ${1:0 0};\n  s:enlist ${2:120 80};\n  fill:enlist ${3:Color.GOLD};\n  alpha:enlist ${4:1}\n)];',
  },
  {
    label: '/pixel',
    detail: 'Snippet',
    documentation: 'Inserts a pixel command scaffold.',
    insertText:
      'pixel[([]\n  p:enlist ${1:0 0};\n  fill:enlist ${2:Color.BLUE};\n  alpha:enlist ${3:1}\n)];',
  },
  {
    label: '/line',
    detail: 'Snippet',
    documentation: 'Inserts a line command scaffold.',
    insertText:
      'line[([]\n  p:enlist ${1:0 0};\n  p2:enlist ${2:100 100};\n  stroke:enlist ${3:Color.INK};\n  width:enlist ${4:2}\n)];',
  },
  {
    label: '/text',
    detail: 'Snippet',
    documentation: 'Inserts a text command scaffold.',
    insertText:
      'text[([]\n  p:enlist ${1:40 40};\n  text:enlist ${2:"hello"};\n  fill:enlist ${3:Color.INK};\n  alpha:enlist ${4:1}\n)];',
  },
  {
    label: '/image',
    detail: 'Snippet',
    documentation: 'Inserts an image command scaffold.',
    insertText:
      'image[([]\n  src:enlist ${1:"assets/example.png"};\n  p:enlist ${2:0 0};\n  s:enlist ${3:128 128};\n  alpha:enlist ${4:1}\n)];',
  },
  {
    label: '/translate',
    detail: 'Snippet',
    documentation: 'Inserts a translate transform command.',
    insertText: 'translate[${1:0 0}];',
  },
  {
    label: '/scale',
    detail: 'Snippet',
    documentation: 'Inserts a scale transform command.',
    insertText: 'scale[${1:1}];',
  },
  {
    label: '/pushpop',
    detail: 'Snippet',
    documentation: 'Wraps drawing commands in push/pop.',
    insertText: 'push[];\n${1:/ drawing commands}\npop[];',
  },
];
