import type { QValue } from "@qpad/core";
import { Session } from "./session.js";
import { formatBare } from "./values.js";
import type { EvalResult, FormatOptions, HostAdapter } from "./types.js";

export const createSession = (host?: HostAdapter) => new Session(host);

export const evaluate = (source: string, session = createSession()): EvalResult =>
  session.evaluate(source);

export const formatValue = (
  value: QValue,
  options: FormatOptions = { trailingNewline: true }
): string => {
  const text = formatBare(value);
  return options.trailingNewline === false ? text : `${text}\n`;
};

export const listBuiltins = () => ({
  monads: [
    "abs",
    "all",
    "any",
    "avgs",
    "til",
    "ceiling",
    "cols",
    "count",
    "desc",
    "differ",
    "exp",
    "fills",
    "first",
    "last",
    "log",
    "min",
    "mins",
    "max",
    "maxs",
    "med",
    "asc",
    "iasc",
    "idesc",
    "asin",
    "atan",
    "sum",
    "avg",
    "asin",
    "acos",
    "atan",
    "sin",
    "cos",
    "tan",
    "floor",
    "null",
    "reciprocal",
    "reverse",
    "signum",
    "sqrt",
    "neg",
    "not",
    "enlist",
    "distinct",
    "attr",
    "flip",
    "group",
    "key",
    "keys",
    "lower",
    "ltrim",
    "next",
    "upper",
    "cut",
    "prd",
    "prds",
    "prev",
    "raze",
    "ratios",
    "rtrim",
    "var",
    "svar",
    "dev",
    "sdev",
    "deltas",
    "trim",
    "sums",
    "string",
    "type",
    "where",
    "value",
    "show",
    "system",
    "hopen",
    "hclose",
    "hcount",
    "hdel",
    "read0",
    "read1",
    "inv",
    "rank",
    "rand",
    "hsym",
    "get",
    "getenv",
    "gtime",
    "ltime",
    "parse",
    "eval",
    "tables",
    "views"
  ],
  diads: [
    "+",
    "-",
    "*",
    "%",
    "=",
    "<",
    ">",
    "<=",
    ">=",
    ",",
    "!",
    "#",
    "_",
    "~",
    "div",
    "mavg",
    "mcount",
    "mdev",
    "msum",
    "mod",
    "^",
    "?",
    "$",
    "@",
    "and",
    "in",
    "like",
    "|",
    "&",
    "cross",
    "or",
    "over",
    "prior",
    "scan",
    "ss",
    "sv",
    "vs",
    "within",
    "except",
    "inter",
    "union",
    "xbar",
    "xexp",
    "xlog",
    "cut",
    "xcol",
    "rotate",
    "sublist",
    "xasc",
    "xdesc",
    "xkey",
    "xgroup",
    "lj",
    "ljf",
    "ij",
    "uj",
    "pj",
    "asof",
    "ssr",
    "mmu",
    "wsum",
    "wavg",
    "bin",
    "binr",
    "xcols",
    "insert",
    "upsert",
    "peach",
    "set"
  ],
  triads: ["aj", "aj0", "ajf", "ajf0", "ej"],
  quads: ["wj", "wj1"]
});
