// Reference catalog: every primitive, keyword and Qanvas function.
// Descriptions are original, written for learners.

export type RefKind = "glyph" | "keyword" | "iterator" | "draw" | "input" | "helper" | "system" | "complex";

export interface RefEntry {
  name: string;
  kind: RefKind;
  cat: string;
  sig: string;
  summary: string;
  detail?: string;
  ex: string[];
  see?: string[];
}

const e = (name: string, kind: RefKind, cat: string, sig: string, summary: string, ex: string[], detail?: string, see?: string[]): RefEntry => ({
  name, kind, cat, sig, summary, ex, detail, see,
});

export const REFERENCE: RefEntry[] = [
  // ---------------- glyph operators ----------------
  e("+", "glyph", "Arithmetic", "x+y   ·   +x (flip)", "Add. Works item-by-item on lists, and an atom pairs with every item.", ["2+3", "1 2 3+10", "1 2 3+10 20 30", "+(1 2 3;4 5 6)"], "The one-argument form flips (transposes) a list of rows, a dictionary of columns, or a table.", ["-", "flip", "sum"]),
  e("-", "glyph", "Arithmetic", "x-y   ·   -x", "Subtract, item-by-item. With one argument it negates.", ["10-3", "10-1 2 3", "neg 1 2 3"], "Watch the spacing: `x-1` subtracts, but `x -1` applies x to negative one.", ["+", "neg"]),
  e("*", "glyph", "Arithmetic", "x*y   ·   *x (first)", "Multiply, item-by-item. With one argument it returns the first item.", ["3*4", "2*til 5", "*10 20 30"], undefined, ["%", "first"]),
  e("%", "glyph", "Arithmetic", "x%y", "Divide. Always gives a float — q uses % because / is taken by 'over'.", ["7%2", "1 2 3%2", "1%0"], "Dividing by zero gives infinity (0w) and 0%0 gives null (0n) rather than an error.", ["div", "reciprocal"]),
  e("!", "glyph", "Structure", "k!v   ·   !n", "Make a dictionary from keys and values. With a number, count up like til.", ["`a`b`c!1 2 3", "!5", "1!([]k:1 2;v:3 4)"], "n!table makes the first n columns the key of a keyed table.", ["key", "value", "til"]),
  e("&", "glyph", "Logic", "x&y   ·   &b (where)", "Minimum of each pair (logical AND for booleans). With one argument: where.", ["3&5", "1 5 3&4", "&0 1 1 0b"], undefined, ["|", "where", "min"]),
  e("|", "glyph", "Logic", "x|y   ·   |x (reverse)", "Maximum of each pair (logical OR for booleans). With one argument: reverse.", ["3|5", "1 5 3|4", "|1 2 3"], undefined, ["&", "reverse", "max"]),
  e("=", "glyph", "Comparison", "x=y   ·   =x (group)", "Equal, item-by-item, giving booleans. With one argument: group.", ["1 2 3=2", "\"abc\"=\"abd\"", "=`a`b`a"], "Floats compare with a tiny tolerance, so 0.1+0.2=0.3 is true.", ["~", "<>", "group"]),
  e("<", "glyph", "Comparison", "x<y   ·   <x (iasc)", "Less than. With one argument: the indices that would sort ascending.", ["1 2 3<2", "<30 10 20"], undefined, [">", "iasc"]),
  e(">", "glyph", "Comparison", "x>y   ·   >x (idesc)", "Greater than. With one argument: the indices that would sort descending.", ["1 2 3>2", ">30 10 20"], undefined, ["<", "idesc"]),
  e("<=", "glyph", "Comparison", "x<=y", "Less than or equal.", ["1 2 3<=2"], undefined, ["<"]),
  e(">=", "glyph", "Comparison", "x>=y", "Greater than or equal.", ["1 2 3>=2"], undefined, [">"]),
  e("<>", "glyph", "Comparison", "x<>y", "Not equal.", ["1 2 3<>2"], undefined, ["="]),
  e("~", "glyph", "Comparison", "x~y   ·   ~x (not)", "Match: 1b if two whole values are identical (type included). With one argument: not.", ["1 2 3~1 2 3", "1~1.0", "~1 0 1b"], undefined, ["=", "not"]),
  e(",", "glyph", "Structure", "x,y   ·   ,x (enlist)", "Join two lists (or atoms) end to end. With one argument: make a one-item list.", ["1 2,3 4", "\"ab\",\"cd\"", ",5"], "Joining tables appends rows; joining dictionaries merges keys (right wins).", ["enlist", "raze"]),
  e("^", "glyph", "Structure", "x^y   ·   ^x (null)", "Fill: replace the nulls in y with x. With one argument: which items are null.", ["0^1 0N 3", "^1 0N 3"], undefined, ["null", "fills"]),
  e("#", "glyph", "Structure", "n#x   ·   #x (count)", "Take n items (cycling if needed; negative takes from the end). With one argument: count.", ["3#til 10", "-2#til 10", "5#1 2", "2 3#til 6", "#1 2 3"], "`r c#x` reshapes into a matrix. `cols#table` picks columns.", ["_", "count", "sublist"]),
  e("_", "glyph", "Structure", "n_x   ·   _x (floor)", "Drop n items (negative drops from the end). With a list of indices, cut. With one argument: floor.", ["2_til 5", "-2_til 5", "0 2 4_til 6", "_3.7"], undefined, ["#", "cut", "floor"]),
  e("$", "glyph", "Types", "t$x   ·   $x (string)", "Cast x to type t (a name like `float, a char like \"f\", or a number like 9h). Uppercase chars parse text.", ["`float$3", "\"j\"$2.7", "\"J\"$\"42\"", "`$\"abc\"", "$42"], undefined, ["string", "type"]),
  e("?", "glyph", "Search", "x?y   ·   ?x (distinct)", "Find: the index of y in x (count x if absent). n?m draws random numbers. With one argument: distinct.", ["10 20 30?20", "\"hello\"?\"l\"", "5?100", "3?1.0", "-5?10", "?1 1 2 3 3"], "`?[cond;a;b]` picks from a where cond is true, else from b — item by item.", ["distinct", "in", "rand"]),
  e("@", "glyph", "Apply", "f@x   ·   @[x;i;f]   ·   @x (type)", "Apply f to x, or index x at i. @[x;i;f] changes the items at i. With one argument: type.", ["{x*x}@5", "10 20 30@1", "@[1 2 3;1;neg]", "@[1 2 3;0 2;+;100]"], "@[f;x;handler] traps errors: if f x fails, handler gets the error text.", [".", "type"]),
  e(".", "glyph", "Apply", "f . args   ·   .[x;path;f]", "Apply f to a list of arguments, or index deep into nested data.", ["{x+y} . 3 4", "(1 2;3 4) . 1 0", ".[(1 2;3 4);1 0;*;10]"], undefined, ["@", "value"]),
  e(":", "glyph", "Apply", "name:value", "Assign a value to a name. Inside a function, :x returns x early.", ["a:5", "a*2", "{:x*2; 99} 5"], "`a+:1` updates in place. `::` assigns a global from inside a function.", []),
  e("'", "iterator", "Iterators", "f'[x]   ·   f'[x;y]   ·   x f' y", "Each: apply f to every item (or to every pair of items).", ["{x*x}'[1 2 3]", "{x,y}'[1 2;3 4]", "1 2 3,'10 20 30", "count each (1 2;3 4 5)"], "Also written as the keyword `each`. `'[f;g]` composes two functions. Like every iterator, apply it with brackets, parentheses or infix — not prefix.", ["each", "/:", "\\:"]),
  e("/", "iterator", "Iterators", "f/[x]   ·   (f/) x   ·   x f/ y", "Over: fold a list down to one value. With a one-argument f, repeat n times or until it settles.", ["+/[1 2 3 4]", "(+/) 1 2 3 4", "10 +/1 2 3", "{x*2}/[5;1]"], "Apply it with brackets, parentheses, or a starting value on its left — q won't apply +/ prefix by juxtaposition. sum is +/. Careful: a space before / starts a comment!", ["\\", "over", "sum"]),
  e("\\", "iterator", "Iterators", "f\\[x]   ·   (f\\) x   ·   x f\\ y", "Scan: like over, but keeps every intermediate result.", ["+\\[1 2 3 4]", "(+\\) 1 2 3 4", "{x*2}\\[5;1]", "{x<100}{x*2}\\1"], "Running totals, random walks and orbits are all scans. sums is +\\.", ["/", "scan", "sums"]),
  e("':", "iterator", "Iterators", "f': x", "Each-prior: apply f to each item and the one before it.", ["-':[1 4 9 16]", "{x-y}':[1 4 9]"], undefined, ["deltas", "prior"]),
  e("/:", "iterator", "Iterators", "x f/: y", "Each-right: keep x fixed and apply f with each item of y.", ["1 2 3,/:10 20", "10 20+/:1 2 3"], undefined, ["\\:", "'"]),
  e("\\:", "iterator", "Iterators", "x f\\: y", "Each-left: apply f with each item of x and the whole of y.", ["1 2 3,\\:10 20", "(1 2;3 4)*\\:10"], "Handy with points: (xs;ys)*\\:s scales every point by its own s.", ["/:", "'"]),

  // ---------------- keywords: math ----------------
  e("abs", "keyword", "Math", "abs x", "Absolute value.", ["abs -3 0 4"]),
  e("neg", "keyword", "Math", "neg x", "Negate.", ["neg 1 -2 3"]),
  e("sqrt", "keyword", "Math", "sqrt x", "Square root (a float).", ["sqrt 2", "sqrt 1 4 9"]),
  e("exp", "keyword", "Math", "exp x", "e raised to the power x.", ["exp 1", "exp 0 1 2"]),
  e("log", "keyword", "Math", "log x", "Natural logarithm.", ["log 10", "log exp 2"]),
  e("xexp", "keyword", "Math", "x xexp y", "x to the power y.", ["2 xexp 10", "2 xexp 0 1 2 3"]),
  e("xlog", "keyword", "Math", "x xlog y", "Logarithm of y in base x.", ["2 xlog 1024"]),
  e("sin", "keyword", "Math", "sin x", "Sine (radians).", ["sin 0 1.5708", "sin .qv.pi*til[5]%4"]),
  e("cos", "keyword", "Math", "cos x", "Cosine (radians).", ["cos 0"]),
  e("tan", "keyword", "Math", "tan x", "Tangent (radians).", ["tan 0.5"]),
  e("asin", "keyword", "Math", "asin x", "Arcsine.", ["asin 1"]),
  e("acos", "keyword", "Math", "acos x", "Arccosine. acos -1 is π.", ["acos -1"]),
  e("atan", "keyword", "Math", "atan x", "Arctangent.", ["atan 1"]),
  e("floor", "keyword", "Math", "floor x", "Round down to a whole number.", ["floor 2.7 -2.7"]),
  e("ceiling", "keyword", "Math", "ceiling x", "Round up to a whole number.", ["ceiling 2.1 -2.1"]),
  e("signum", "keyword", "Math", "signum x", "-1, 0 or 1 by sign.", ["signum -5 0 5"]),
  e("reciprocal", "keyword", "Math", "reciprocal x", "1 divided by x.", ["reciprocal 2 4"]),
  e("mod", "keyword", "Math", "x mod y", "Remainder after dividing x by y (always the sign of y).", ["7 mod 3", "til[10] mod 3", "-7 mod 3"]),
  e("div", "keyword", "Math", "x div y", "Whole-number division, rounding down.", ["7 div 2", "-7 div 2"]),
  e("xbar", "keyword", "Math", "x xbar y", "Round y down to a multiple of x — perfect for buckets and grids.", ["10 xbar 3 17 25", "0.5 xbar 1.3 2.8"]),
  e("sum", "keyword", "Aggregate", "sum x", "Add up a list (nulls are skipped). On rows (xs;ys) it adds the rows together.", ["sum 1 2 3", "sum (1 2;10 20)"], undefined, ["sums", "+"]),
  e("prd", "keyword", "Aggregate", "prd x", "Multiply a list together.", ["prd 1 2 3 4"]),
  e("max", "keyword", "Aggregate", "max x", "Largest item.", ["max 3 1 4"]),
  e("min", "keyword", "Aggregate", "min x", "Smallest item.", ["min 3 1 4"]),
  e("avg", "keyword", "Aggregate", "avg x", "Mean (a float).", ["avg 1 2 3 4"]),
  e("med", "keyword", "Aggregate", "med x", "Median.", ["med 5 1 3 9"]),
  e("var", "keyword", "Aggregate", "var x", "Variance.", ["var 1 2 3 4"]),
  e("dev", "keyword", "Aggregate", "dev x", "Standard deviation.", ["dev 1 2 3 4"]),
  e("sdev", "keyword", "Aggregate", "sdev x", "Sample standard deviation.", ["sdev 1 2 3 4"]),
  e("count", "keyword", "Aggregate", "count x", "How many items.", ["count 1 2 3", "count \"hello\"", "count 5"]),
  e("all", "keyword", "Aggregate", "all x", "1b if every item is true (non-zero).", ["all 1 1 0b", "all 3>1 2"]),
  e("any", "keyword", "Aggregate", "any x", "1b if any item is true.", ["any 0 0 1b"]),
  e("wavg", "keyword", "Aggregate", "w wavg x", "Weighted average.", ["1 2 3 wavg 10 20 30"]),
  e("wsum", "keyword", "Aggregate", "w wsum x", "Weighted sum.", ["1 2 3 wsum 10 20 30"]),
  e("cor", "keyword", "Aggregate", "x cor y", "Correlation between two lists.", ["1 2 3 cor 2 4 7"]),
  e("cov", "keyword", "Aggregate", "x cov y", "Covariance.", ["1 2 3 cov 2 4 6"]),
  e("sums", "keyword", "Running", "sums x", "Running totals.", ["sums 1 2 3 4"], undefined, ["sum", "\\"]),
  e("prds", "keyword", "Running", "prds x", "Running products.", ["prds 1 2 3 4"]),
  e("maxs", "keyword", "Running", "maxs x", "Running maximum.", ["maxs 3 1 4 1 5"]),
  e("mins", "keyword", "Running", "mins x", "Running minimum.", ["mins 3 1 4 1 5"]),
  e("avgs", "keyword", "Running", "avgs x", "Running average.", ["avgs 1 2 3 4"]),
  e("deltas", "keyword", "Running", "deltas x", "Differences between neighbours (first item kept).", ["deltas 1 4 9 16"]),
  e("ratios", "keyword", "Running", "ratios x", "Ratios between neighbours.", ["ratios 1 2 6 24"]),
  e("differ", "keyword", "Running", "differ x", "1b where an item differs from the one before.", ["differ 1 1 2 2 3"]),
  e("mavg", "keyword", "Running", "n mavg x", "Moving average over a window of n.", ["3 mavg 1 2 3 4 5"]),
  e("msum", "keyword", "Running", "n msum x", "Moving sum.", ["3 msum 1 2 3 4 5"]),
  e("mmax", "keyword", "Running", "n mmax x", "Moving maximum.", ["2 mmax 1 3 2 5"]),
  e("mmin", "keyword", "Running", "n mmin x", "Moving minimum.", ["2 mmin 1 3 2 5"]),
  e("ema", "keyword", "Running", "a ema x", "Exponential moving average with smoothing a.", ["0.5 ema 1 2 3 4"]),
  e("prev", "keyword", "Running", "prev x", "Shift right by one (first becomes null).", ["prev 1 2 3"]),
  e("next", "keyword", "Running", "next x", "Shift left by one.", ["next 1 2 3"]),
  e("xprev", "keyword", "Running", "n xprev x", "Shift right by n.", ["2 xprev 1 2 3 4"]),
  e("fills", "keyword", "Running", "fills x", "Fill nulls with the last non-null value.", ["fills 1 0N 0N 4"]),

  // ---------------- lists ----------------
  e("til", "keyword", "Lists", "til n", "The first n whole numbers, starting from 0. The heartbeat of array code.", ["til 10", "2*til 5", "til 0"], "Almost every sketch starts with til: `til 100` gives you 100 things to draw.", ["!", "#"]),
  e("first", "keyword", "Lists", "first x", "First item.", ["first 10 20 30"]),
  e("last", "keyword", "Lists", "last x", "Last item.", ["last 10 20 30"]),
  e("reverse", "keyword", "Lists", "reverse x", "Items in reverse order.", ["reverse 1 2 3", "reverse \"stressed\""]),
  e("enlist", "keyword", "Lists", "enlist x", "Wrap in a one-item list.", ["enlist 5", "enlist 1 2 3"]),
  e("raze", "keyword", "Lists", "raze x", "Flatten one level: join the items together.", ["raze (1 2;3;4 5)"]),
  e("where", "keyword", "Lists", "where b", "Indices of the true items in a boolean list — the heart of filtering.", ["where 0 1 1 0 1b", "x:3 8 1 9; where x>2", "x where x>2"], "With counts, repeats each index: where 2 0 3.", ["?", "&"]),
  e("distinct", "keyword", "Lists", "distinct x", "Unique items, in order of first appearance.", ["distinct 3 1 3 2 1"]),
  e("group", "keyword", "Lists", "group x", "A dictionary from each distinct item to the indices where it appears.", ["group `a`b`a`c`b"]),
  e("asc", "keyword", "Lists", "asc x", "Sort ascending.", ["asc 3 1 2", "asc \"banana\""]),
  e("desc", "keyword", "Lists", "desc x", "Sort descending.", ["desc 3 1 2"]),
  e("iasc", "keyword", "Lists", "iasc x", "Indices that sort x ascending.", ["iasc 30 10 20"]),
  e("idesc", "keyword", "Lists", "idesc x", "Indices that sort x descending.", ["idesc 30 10 20"]),
  e("rank", "keyword", "Lists", "rank x", "Position of each item in sorted order.", ["rank 30 10 20"]),
  e("in", "keyword", "Lists", "x in y", "1b for each item of x that appears in y.", ["2 5 in 1 2 3", "\"hello\" in \"aeiou\""]),
  e("within", "keyword", "Lists", "x within (lo;hi)", "1b where lo <= x <= hi.", ["3 7 12 within 5 10"]),
  e("except", "keyword", "Lists", "x except y", "Items of x not in y.", ["1 2 3 4 except 2 4"]),
  e("inter", "keyword", "Lists", "x inter y", "Items in both.", ["1 2 3 inter 2 3 4"]),
  e("union", "keyword", "Lists", "x union y", "Distinct items from either.", ["1 2 3 union 3 4"]),
  e("cross", "keyword", "Lists", "x cross y", "Every pairing of an item of x with an item of y.", ["1 2 cross 10 20"], "`flip til[3] cross til[3]` gives the points of a 3×3 grid as rows (xs;ys).", ["grid"]),
  e("rotate", "keyword", "Lists", "n rotate x", "Rotate items left by n (right if negative).", ["1 rotate 1 2 3 4", "-1 rotate 1 2 3 4"]),
  e("cut", "keyword", "Lists", "n cut x", "Cut into pieces of n items.", ["3 cut til 10"]),
  e("sublist", "keyword", "Lists", "n sublist x", "Take up to n items (never pads).", ["3 sublist 1 2", "1 2 sublist til 10"]),
  e("bin", "keyword", "Lists", "x bin y", "For sorted x, the index of the last item <= y.", ["0 10 20 30 bin 15 25"]),
  e("flip", "keyword", "Lists", "flip x", "Transpose: rows become columns. Turns a list of pairs into rows (xs;ys), and a dictionary of columns into a table.", ["flip (1 2;3 4;5 6)", "flip `a`b!(1 2;3 4)"], undefined, ["+"]),
  e("next", "keyword", "Lists", "next x", "Shift items left by one.", ["next 1 2 3"]),
  e("rand", "keyword", "Lists", "rand x", "One random item (or number below x).", ["rand 10", "rand `rock`paper`scissors"]),

  // ---------------- dictionaries & tables ----------------
  e("key", "keyword", "Dictionaries", "key d", "Keys of a dictionary (or the key columns of a keyed table). With a number, like til.", ["key `a`b!1 2", "key 3"]),
  e("value", "keyword", "Dictionaries", "value d", "Values of a dictionary. On a string, evaluates it as q code.", ["value `a`b!1 2", "value \"2+3\""]),
  e("cols", "keyword", "Tables", "cols t", "Column names of a table.", ["cols ([]a:1 2;b:3 4)"]),
  e("meta", "keyword", "Tables", "meta t", "Column names and types of a table.", ["meta ([]a:1 2;b:`x`y)"]),
  e("select", "keyword", "qSQL", "select cols by g from t where c", "Query a table: choose columns, filter rows, group and aggregate.", [
    "t:([]name:`a`b`c`d;n:3 8 1 9)", "select from t where n>2", "select name from t where n>2", "select total:sum n by n>5 from t",
  ]),
  e("update", "keyword", "qSQL", "update c:e from t where ...", "Add or change columns (only on matching rows, if there's a where).", ["t:([]n:1 2 3)", "update m:n*10 from t", "update n:0 from t where n>1"]),
  e("delete", "keyword", "qSQL", "delete from t where ...", "Remove rows (or columns: delete c from t).", ["t:([]n:1 2 3)", "delete from t where n=2"]),
  e("exec", "keyword", "qSQL", "exec col from t", "Like select, but returns plain lists (or a dictionary) instead of a table.", ["t:([]n:1 2 3)", "exec n from t"]),
  e("xasc", "keyword", "Tables", "c xasc t", "Sort a table by column(s), ascending.", ["`n xasc ([]n:3 1 2)"]),
  e("xdesc", "keyword", "Tables", "c xdesc t", "Sort a table by column(s), descending.", ["`n xdesc ([]n:3 1 2)"]),
  e("xkey", "keyword", "Tables", "c xkey t", "Make column(s) the key.", ["`k xkey ([]k:`a`b;v:1 2)"]),
  e("xcol", "keyword", "Tables", "names xcol t", "Rename columns.", ["`x`y xcol ([]a:1 2;b:3 4)"]),
  e("lj", "keyword", "Tables", "t lj kt", "Left join: add columns from a keyed table, matched on its key.", ["([]k:`a`b`c) lj ([k:`a`b]v:1 2)"]),
  e("ij", "keyword", "Tables", "t ij kt", "Inner join: only the rows with a match.", ["([]k:`a`b`c) ij ([k:`a`b]v:1 2)"]),
  e("uj", "keyword", "Tables", "t uj u", "Union join: stack tables, merging columns.", ["([]a:1 2) uj ([]b:3 4)"]),
  e("aj", "keyword", "Tables", "aj[c;t;q]", "As-of join: for each row, the latest matching row of q at or before its time.", ["aj[`t;([]t:1 5 9);([]t:0 4 8;v:`a`b`c)]"]),
  e("insert", "keyword", "Tables", "`t insert row", "Append rows to a global table.", ["t:([]a:1 2)", "`t insert 3", "t"]),
  e("upsert", "keyword", "Tables", "t upsert row", "Insert, or update rows with a matching key.", ["([k:1 2]v:10 20) upsert (2;99)"]),
  e("ungroup", "keyword", "Tables", "ungroup t", "Spread list-valued cells into one row each.", ["ungroup ([]a:1 2;b:(3 4;5 6 7))"]),
  e("fby", "keyword", "qSQL", "(f;col) fby g", "Aggregate within groups, inside a where clause.", ["t:([]g:`a`a`b;n:1 5 3)", "select from t where n=(max;n) fby g"]),

  // ---------------- strings ----------------
  e("string", "keyword", "Strings", "string x", "Text form of a value.", ["string 42", "string `abc", "string 1 2 3"]),
  e("upper", "keyword", "Strings", "upper s", "Upper case.", ["upper \"hello\""]),
  e("lower", "keyword", "Strings", "lower s", "Lower case.", ["lower \"HELLO\""]),
  e("trim", "keyword", "Strings", "trim s", "Remove spaces from both ends.", ["trim \"  hi  \""]),
  e("like", "keyword", "Strings", "s like pattern", "Match against a pattern with * (anything) and ? (one char).", ["\"hello\" like \"h*o\"", "`apple`banana like \"*an*\""]),
  e("ss", "keyword", "Strings", "s ss pattern", "Positions where a pattern occurs, including overlaps.", ["\"banana\" ss \"an\"", "\"aaa\" ss \"aa\""]),
  e("ssr", "keyword", "Strings", "ssr[s;find;replace]", "Search and replace.", ["ssr[\"banana\";\"an\";\"AN\"]"]),
  e("vs", "keyword", "Strings", "sep vs s", "Split a string on a separator. An empty symbol on the left splits text into lines.", ["\",\" vs \"a,b,c\"", "` vs \"a\\nb\""]),
  e("sv", "keyword", "Strings", "sep sv strings", "Join strings with a separator ('scalar from vector').", ["\"-\" sv (\"ab\";\"cd\";\"ef\")"]),

  // ---------------- types & misc ----------------
  e("type", "keyword", "Types", "type x", "The type number: negative for atoms, positive for lists (7 long, 9 float, 11 symbol...).", ["type 1", "type 1 2", "type `a", "type 1.5"]),
  e("null", "keyword", "Types", "null x", "1b where x is null.", ["null 1 0N 3"]),
  e("show", "keyword", "System", "show x", "Print a value to the console.", ["show 1 2 3"]),
  e("each", "iterator", "Iterators", "f each x", "Apply f to every item of x.", ["{x*x} each 1 2 3", "count each (\"ab\";\"cde\")"], undefined, ["'"]),
  e("over", "iterator", "Iterators", "f over x", "Same as f/ — fold.", ["(+) over 1 2 3"]),
  e("scan", "iterator", "Iterators", "f scan x", "Same as f\\ — running fold.", ["(+) scan 1 2 3"]),
  e("prior", "iterator", "Iterators", "f prior x", "Same as f': — apply to each item and the one before.", ["(-) prior 1 4 9"]),
  e("mmu", "keyword", "Math", "x mmu y", "Matrix multiply (or dot product of two vectors).", ["(1 2;3 4) mmu (1 0;0 1f)", "1 2 3f mmu 4 5 6f"], "Rotating a cloud of points (xs;ys) is one mmu with a 2×2 rotation matrix."),
  e("inv", "keyword", "Math", "inv m", "Matrix inverse.", ["inv (2 0;0 4f)"]),
  e("if", "keyword", "Control", "if[cond; a; b; ...]", "Run the statements only if cond is true. (Most q code uses $[ ] or where instead.)", ["{if[x>5; :`big]; `small} 7"]),
  e("do", "keyword", "Control", "do[n; ...]", "Repeat statements n times.", ["r:0; do[5; r+:2]; r"]),
  e("while", "keyword", "Control", "while[cond; ...]", "Repeat while cond is true.", ["i:1; while[i<100; i*:2]; i"]),
  e("$[", "keyword", "Control", "$[cond; then; else]", "Conditional expression. Add more cond;then pairs for else-if chains.", ["$[1>0;`yes;`no]", "{$[x<0;`neg;x=0;`zero;`pos]} each -1 0 1"]),
  e("parse", "keyword", "System", "parse s", "The parse tree of a string of q code.", ["parse \"1+2*3\""]),
  e("get", "keyword", "System", "get `name", "The value of a global by name.", ["a:5; get `a"]),
  e("set", "keyword", "System", "`name set v", "Assign a global by name.", ["`b set 10; b"]),

  // ---------------- Qanvas drawing ----------------
  e("canvas", "draw", "Canvas", "canvas w h", "Set the canvas size in pixels (default 600 600).", ["canvas 800 400"], undefined, ["size", "width", "height"]),
  e("background", "draw", "Canvas", "background c", "Fill the whole canvas with a colour. Call it first thing in draw to clear the last frame.", ["background 20", "background `coral", "background 30 20 60"]),
  e("clear", "draw", "Canvas", "clear[]", "Make the canvas transparent.", ["clear[]"]),
  e("circle", "draw", "Shapes", "circle[p;r]", "Circles at point(s) p with radius r. p is one point `x y` or many as rows (xs;ys); r is one radius or one per circle.", [
    "circle[300 300;100]", "circle[(100 200 300;300);20]", "circle[(50*1+til 10;300);3*1+til 10]",
  ], "One call can draw thousands of circles — that's the array way."),
  e("ellipse", "draw", "Shapes", "ellipse[p;r]", "Ellipses: r is an x y pair of radii (or rows of them).", ["ellipse[300 300;200 80]"]),
  e("rect", "draw", "Shapes", "rect[p;wh]", "Rectangles with top-left corner p and size wh (one number for squares).", ["rect[100 100;200 50]", "rect[(til[10]*60;100);40]"]),
  e("square", "draw", "Shapes", "square[p;s]", "Squares with corner p and side s.", ["square[(50*til 10;50*til 10);40]"]),
  e("line", "draw", "Shapes", "line[a;b]", "Lines from point(s) a to point(s) b, using the pen colour.", ["line[0 0;600 600]", "line[(0;60*til 10);(600;600-60*til 10)]"]),
  e("point", "draw", "Shapes", "point p", "Dots at point(s) p, sized by weight.", ["weight 4; point (600?600f;600?600f)"]),
  e("poly", "draw", "Shapes", "poly p", "A filled polygon through the points (xs;ys). A list of those draws many polygons.", ["poly (300 500 100;100 500 500)"]),
  e("path", "draw", "Shapes", "path p", "An open line through the points (xs;ys) — great for graphs.", ["x:til 600; path (x;300+100*sin x%50)"]),
  e("curve", "draw", "Shapes", "curve p", "A smooth curve through the points (xs;ys).", ["curve (100 200 300 400 500;300 100 500 100 300)"]),
  e("blob", "draw", "Shapes", "blob p", "A smooth closed, filled shape through the points.", ["blob center+120*(cos a;sin a:6.28*til[7]%7)"]),
  e("tri", "draw", "Shapes", "tri[a;b;c]", "Triangles with corners a, b, c.", ["tri[300 100;100 500;500 500]"]),
  e("arc", "draw", "Shapes", "arc[p;r;a0 a1]", "A pie slice from angle a0 to a1 (radians).", ["arc[300 300;150;0 2]"]),
  e("text", "draw", "Shapes", "text[p;s]", "Write text at p. Numbers and other values are shown in q form.", ["font 40; text[100 300;\"hello q\"]", "text[(100 200 300;300);`a`b`c]"]),
  e("pixels", "draw", "Images", "pixels m", "Draw a matrix of numbers as an image filling the canvas: 0..1 or 0..255 grays, or (r;g;b) matrices.", ["pixels {x*\\:x} til[64]%63"]),
  e("heatmap", "draw", "Images", "heatmap m   ·   heatmap[m;`magma]", "Draw a matrix through a colour map (auto-scaled). Maps: viridis magma inferno plasma ocean fire ice gray rainbow.", ["heatmap {sin x+/:y}[til[60]%9;til[60]%9]"]),
  e("ink", "draw", "Style", "ink c", "Fill colour for the next shapes. One colour, or one per shape as rows (r;g;b). `none turns fill off.", ["ink `coral; circle[300 300;100]", "ink 255 200 0", "ink hsb[til[10]%10;1;1]"]),
  e("pen", "draw", "Style", "pen c", "Outline colour for the next shapes. `none turns outlines off.", ["pen 255; weight 3; ink `none; circle[300 300;100]"]),
  e("weight", "draw", "Style", "weight w", "Line thickness.", ["weight 8; pen `sky; line[0 0;600 600]"]),
  e("alpha", "draw", "Style", "alpha a", "Opacity for everything after, from 0 (invisible) to 255.", ["alpha 100"]),
  e("blend", "draw", "Style", "blend `mode", "How new colour mixes with the canvas: `normal `add `multiply `screen `difference...", ["blend `add"]),
  e("font", "draw", "Style", "font 24   ·   font `mono", "Text size, or face (`sans `serif `mono).", ["font 32"]),
  e("align", "draw", "Style", "align `center", "Text alignment: `left`center`right and `top`middle`bottom.", ["align `center`middle"]),
  e("move", "draw", "Transform", "move x y", "Shift the origin for everything drawn after.", ["move center; circle[0 0;50]"]),
  e("turn", "draw", "Transform", "turn a", "Rotate everything after by a radians.", ["move center; turn 0.3; rect[-50 -50;100]"]),
  e("zoom", "draw", "Transform", "zoom s", "Scale everything after (one number or x y).", ["zoom 2; circle[100 100;20]"]),
  e("push", "draw", "Transform", "push[]", "Save the current style and transform…", ["push[]; move 100 100; circle[0 0;10]; pop[]"]),
  e("pop", "draw", "Transform", "pop[]", "…and restore them.", []),
  e("hsb", "helper", "Colour", "hsb[h;s;b]", "Colour from hue, saturation, brightness (each 0..1; hue wraps around). Works on whole lists.", ["hsb[0.6;0.8;1]", "hsb[til[5]%5;1;1]"]),
  e("rgb", "helper", "Colour", "rgb[r;g;b]", "Colour from red, green, blue (0..255).", ["rgb[255;128;0]"]),
  e("gray", "helper", "Colour", "gray v", "One gray per shape, as colour rows.", ["gray 0 128 255"]),
  e("noise", "helper", "Nature", "noise x   ·   noise (xs;ys)", "Smooth Perlin noise between 0 and 1. Nearby inputs give nearby outputs.", ["noise 0.1 0.2 0.3", "noise (til[5]%10;0.5)"]),
  e("noiseseed", "helper", "Nature", "noiseseed n", "Choose a different noise landscape.", ["noiseseed 42"]),
  e("fps", "draw", "Canvas", "fps n", "Frames per second for draw (default 60).", ["fps 12"]),
  e("noloop", "draw", "Canvas", "noloop[]", "Stop calling draw.", []),
  e("tone", "helper", "Sound", "tone[freq;seconds]", "Play a note (Hz). A list of frequencies plays a chord.", ["tone[440;0.5]", "tone[261.6 329.6 392;1]"]),
  e("mic", "helper", "Sound", "mic[]", "Start listening. Then read level (0..1) and spectrum (64 bands).", []),
  e("camera", "helper", "Camera", "camera 64 48", "Start the webcam. Then cam is a matrix of grays (0..1); camrgb is (r;g;b).", []),

  // inputs & values
  e("mouse", "input", "Input", "mouse", "The pointer position as x y.", ["mouse"]),
  e("pmouse", "input", "Input", "pmouse", "Where the pointer was last frame.", []),
  e("mousedown", "input", "Input", "mousedown", "1b while the mouse button (or a finger) is down.", []),
  e("clicked", "input", "Input", "clicked", "1b on the frame the mouse was pressed.", []),
  e("released", "input", "Input", "released", "1b on the frame the mouse was released.", []),
  e("held", "input", "Input", "held", "Symbols of the keys held down right now, e.g. `left`space.", ["`space in held"]),
  e("pressed", "input", "Input", "pressed", "Keys pressed this frame.", []),
  e("touches", "input", "Input", "touches", "Every finger on the screen, as rows (xs;ys).", []),
  e("wheel", "input", "Input", "wheel", "Scroll wheel movement this frame.", []),
  e("frame", "input", "Time", "frame", "How many frames have been drawn (0, 1, 2, …).", []),
  e("time", "input", "Time", "time", "Seconds since the sketch started.", ["sin time"]),
  e("dt", "input", "Time", "dt", "Seconds since the last frame.", []),
  e("size", "input", "Canvas", "size", "Canvas size as w h.", ["size", "size%2"]),
  e("width", "input", "Canvas", "width", "Canvas width.", []),
  e("height", "input", "Canvas", "height", "Canvas height.", []),
  e("center", "input", "Canvas", "center", "The middle of the canvas, as x y.", ["center"]),
  e("level", "input", "Sound", "level", "Microphone loudness, 0..1 (after mic[]).", []),
  e("spectrum", "input", "Sound", "spectrum", "64 frequency bands, 0..1 (after mic[]).", []),
  e("cam", "input", "Camera", "cam", "Webcam as a matrix of grays 0..1 (after camera).", []),

  // helpers written in q
  e("pi", "helper", "Maths", "pi", "π, 3.14159…", ["pi", "2*pi"]),
  e("tau", "helper", "Maths", "tau", "2π — one full turn in radians.", ["tau"]),
  e("lerp", "helper", "Maths", "lerp[a;b;t]", "Blend from a to b by t (0..1). Works on points and colours too.", ["lerp[0;100;0.25]", "lerp[0 0;100 200;0.5]"]),
  e("clamp", "helper", "Maths", "clamp[lo;hi;x]", "Keep x between lo and hi.", ["clamp[0;10;-5 5 15]"]),
  e("remap", "helper", "Maths", "remap[x;a;b;c;d]", "Map x from the range a..b to c..d.", ["remap[5;0;10;0;600]"]),
  e("norm", "helper", "Vectors", "norm v", "Length of a vector — or of every column in (xs;ys).", ["norm 3 4", "norm (3 0;4 1)"]),
  e("unit", "helper", "Vectors", "unit v", "Scale vector(s) to length 1.", ["unit 3 4"]),
  e("dist", "helper", "Vectors", "dist[a;b]", "Distance between points (works on whole rows of points).", ["dist[0 0;3 4]"]),
  e("dot", "helper", "Vectors", "dot[a;b]", "Dot product (per column for rows of points).", ["dot[1 2;3 4]"]),
  e("polar", "helper", "Vectors", "polar[r;a]", "Points at radius r and angle a, as rows (xs;ys).", ["polar[100;0 1.57]"]),
  e("angle", "helper", "Vectors", "angle v", "Direction of vector(s), in radians.", ["angle 0 1"]),
  e("rot", "helper", "Vectors", "rot[a;p]", "Rotate point(s) p around the origin by a radians.", ["rot[pi%2;1 0]"]),
  e("ring", "helper", "Vectors", "ring n", "n points evenly around a unit circle, as rows (xs;ys).", ["ring 4"]),
  e("grid", "helper", "Vectors", "grid[w;h]", "Every point of a w×h grid, as rows (xs;ys).", ["grid[3;2]"]),
  e("gauss", "helper", "Maths", "gauss n", "n random numbers from a bell curve (mean 0, spread 1).", ["gauss 5"]),
  e("atan2", "helper", "Maths", "atan2[y;x]", "The angle of (x,y), correctly in every quadrant.", ["atan2[1;1]"]),

  // complex numbers
  e(".cx.new", "complex", "Complex", ".cx.new[re;im]", "A complex number is just a point (re;im) — so a whole grid of them is rows (res;ims).", [".cx.new[1;2]"]),
  e(".cx.mul", "complex", "Complex", ".cx.mul[z;w]", "Multiply complex numbers.", [".cx.mul[1 2f;3 4f]"]),
  e(".cx.sq", "complex", "Complex", ".cx.sq z", "Square — the heart of the Mandelbrot set.", [".cx.sq 0 1f"]),
  e(".cx.add", "complex", "Complex", ".cx.add[z;w]", "Add (plain +, since complex numbers are points).", [".cx.add[1 2f;3 4f]"]),
  e(".cx.abs", "complex", "Complex", ".cx.abs z", "Magnitude |z|.", [".cx.abs 3 4f"]),
  e(".cx.arg", "complex", "Complex", ".cx.arg z", "Angle of z.", [".cx.arg 0 1f"]),
  e(".cx.conj", "complex", "Complex", ".cx.conj z", "Conjugate.", [".cx.conj 1 2f"]),
  e(".cx.div", "complex", "Complex", ".cx.div[z;w]", "Divide.", [".cx.div[1 0f;0 1f]"]),
  e(".cx.exp", "complex", "Complex", ".cx.exp z", "e to the z.", [".cx.exp (0f;pi)"]),
  e(".cx.pow", "complex", "Complex", ".cx.pow[z;n]", "z to the power n.", [".cx.pow[0 1f;2]"]),
  e(".cx.str", "complex", "Complex", ".cx.str z", "Show z as text like 1+2i.", [".cx.str 1 2f"]),
];

export const REF_BY_NAME = new Map(REFERENCE.map((r) => [r.name, r]));

export const KIND_LABEL: Record<RefKind, string> = {
  glyph: "operator", keyword: "keyword", iterator: "iterator", draw: "drawing", input: "input", helper: "helper", system: "system", complex: "complex",
};
