import { createSession, formatValue, listBuiltins } from '@qpad/engine';

export type ReferenceRow = {
  id: string;
  kind: 'primitive' | 'test';
  name: string;
  expression: string;
  expected: string;
  description: string;
  group: string;
};

const descriptions: Record<string, string> = {
  '+': 'Add numbers, join temporal offsets, or reduce with plus adverbs.',
  '-': 'Subtract values; with each-prior it is the basis of deltas.',
  '*': 'Multiply numbers or use as a fast product kernel with adverbs.',
  '%': 'Divide and produce floating-point ratios.',
  '=': 'Compare for equality.',
  '<': 'Less-than comparison.',
  '>': 'Greater-than comparison.',
  '<=': 'Less-than-or-equal comparison.',
  '>=': 'Greater-than-or-equal comparison.',
  ',': 'Join atoms, lists, dictionaries, and table-like data.',
  '!': 'Create dictionaries, enumerate integers, or use keyed forms.',
  '#': 'Take, reshape, or count depending on valence.',
  '_': 'Drop, cut, or floor depending on valence.',
  '~': 'Match values exactly.',
  '|': 'Reverse as a monad; max as a dyad.',
  '&': 'Where as a monad; min as a dyad.',
  '$': 'Cast or conditional selection.',
  '?': 'Find or random/sample depending on arguments.',
  '@': 'Apply or index.',
  '^': 'Fill nulls.',
  abs: 'Absolute value for numeric atoms and lists.',
  all: 'Return whether every boolean item is true.',
  any: 'Return whether any boolean item is true.',
  asc: 'Sort ascending.',
  avg: 'Average numeric data, ignoring q nulls where q does.',
  avgs: 'Running averages.',
  ceiling: 'Round upward.',
  cols: 'Return table column symbols.',
  cor: 'Correlation between numeric series.',
  count: 'Count items.',
  cov: 'Population covariance between numeric series.',
  cut: 'Split a list by size or index cuts.',
  deltas: 'Consecutive differences; q display name is -\':.',
  desc: 'Sort descending.',
  dev: 'Population standard deviation.',
  differ: 'Mark changes from the previous item.',
  distinct: 'Unique items, preserving first occurrence order.',
  div: 'Integer division.',
  dsave: 'Save named tables under a browser-safe database root.',
  ema: 'Exponential moving average.',
  enlist: 'Wrap a value as a single-item list.',
  except: 'Items from the left absent from the right.',
  exp: 'Natural exponent.',
  fills: 'Forward-fill nulls.',
  first: 'First item.',
  flip: 'Flip dictionary columns into a table.',
  floor: 'Round downward.',
  group: 'Map each distinct item to its positions.',
  in: 'Membership test.',
  inter: 'Intersection.',
  inv: 'Matrix inverse.',
  key: 'Dictionary keys, keyed-table key, or namespace contents.',
  keys: 'Alias-style key lookup supported for q familiarity.',
  last: 'Last item.',
  like: 'Wildcard string matching.',
  log: 'Natural logarithm.',
  lower: 'Lowercase strings.',
  lsq: 'Least-squares matrix solve.',
  max: 'Maximum item.',
  maxs: 'Running maximums.',
  md5: 'MD5 hash as a byte vector.',
  mavg: 'Moving average.',
  mcount: 'Moving count of non-null items.',
  mdev: 'Moving standard deviation.',
  med: 'Median.',
  min: 'Minimum item.',
  mins: 'Running minimums.',
  mmax: 'Moving maximum.',
  mmin: 'Moving minimum.',
  msum: 'Moving sum.',
  neg: 'Negate numbers.',
  next: 'Next item, shifted left.',
  not: 'Boolean not.',
  null: 'Detect q nulls.',
  over: 'Adverb spelling for reduction.',
  parse: 'Parse source text where supported.',
  prd: 'Product.',
  prds: 'Running products.',
  prev: 'Previous item, shifted right.',
  prior: 'Adverb spelling for each-prior.',
  rand: 'Random/sample helper.',
  rank: 'Grade/rank values.',
  ratios: 'Consecutive ratios.',
  raze: 'Flatten one level.',
  reciprocal: 'Reciprocal of numeric values.',
  reverse: 'Reverse item order.',
  rload: 'Load a browser-safe splayed table payload.',
  rotate: 'Rotate a list.',
  rsave: 'Save an unkeyed table as a browser-safe splayed payload.',
  scan: 'Adverb spelling for running scan.',
  scov: 'Sample covariance.',
  sdev: 'Sample standard deviation.',
  signum: 'Sign of numeric values.',
  sqrt: 'Square root.',
  ss: 'String search.',
  ssr: 'String search and replace.',
  string: 'Format values as strings.',
  sublist: 'Take a bounded sublist.',
  sum: 'Sum numeric data.',
  sums: 'Running sums.',
  sv: 'Scalar/vector join for strings and symbols.',
  svar: 'Sample variance.',
  til: 'Integers from 0 up to n-1.',
  trim: 'Trim whitespace.',
  type: 'q type code.',
  union: 'Union of distinct values.',
  upper: 'Uppercase strings.',
  value: 'Evaluate q source text or extract dictionary/table values.',
  var: 'Population variance.',
  vs: 'Split string or symbol vectors.',
  wavg: 'Weighted average.',
  where: 'Indices of true boolean values.',
  within: 'Inclusive range membership.',
  wsum: 'Weighted sum.',
  xasc: 'Sort table ascending by column.',
  xbar: 'Bucket values by interval.',
  xcol: 'Rename table columns.',
  xcols: 'Reorder table columns.',
  xdesc: 'Sort table descending by column.',
  xexp: 'Power.',
  xgroup: 'Group a table by column.',
  xkey: 'Key a table by column.',
  xlog: 'Logarithm with a base.'
};

const primitiveSamples: Record<string, string> = {
  '+': '1 2 3+10',
  '-': '10 20 30-1 2 3',
  '*': '2 3 4*10',
  '%': '10%4',
  '=': '1 2 3=2',
  '<': '1 2 3<3',
  '>': '1 2 3>2',
  '<=': '1 2 3<=2',
  '>=': '1 2 3>=2',
  ',': '1 2,3 4',
  '!': '`a`b!1 2',
  '#': '3#1 2',
  '_': '2_1 2 3 4',
  '~': '1 2~1 2',
  '|': '|3 1 2',
  '&': '&10110b',
  '$': '`int$1.5 2.7',
  '?': '10 20 30?20 40',
  '@': '@[10 20 30;1]',
  '^': '0N 2 0N^9',
  acos: 'acos 0 0.5',
  aj: 't:([]s:`a`a`t:1 3;v:10 30);q:([]s:`a`t:2);aj[`s`t;q;t]',
  aj0: 't:([]s:`a`a;t:1 3;v:10 30);q:([]s:`a;t:2);aj0[`s`t;q;t]',
  ajf: 't:([]s:`a`a;t:1 3;v:10 30);q:([]s:`a;t:2;v:0N);ajf[`s`t;q;t]',
  ajf0: 't:([]s:`a`a;t:1 3;v:10 30);q:([]s:`a;t:2;v:0N);ajf0[`s`t;q;t]',
  abs: 'abs -2 3 -4',
  all: 'all 110b',
  and: '1 0 1 and 1 1 0',
  any: 'any 001b',
  asof: '1 3 5 asof 4',
  asc: 'asc 3 1 2',
  asin: 'asin 0 0.5',
  atan: 'atan 0 1',
  attr: 'attr 1 2 3',
  avg: 'avg 1 0n 2 3',
  avgs: 'avgs 1 2 3 4',
  bin: '1 3 5 7 bin 0 1 4 8',
  binr: '1 3 5 7 binr 0 1 4 8',
  ceiling: 'ceiling 1.2 3.0 -1.2',
  cols: 'cols ([]a:1 2;b:3 4)',
  cor: '29 10 54 cor 1 3 9',
  cos: 'cos 0 1',
  count: 'count 10 20 30',
  cov: '2 3 5 7 cov 3 3 5 9',
  cross: '1 2 cross 10 20',
  cut: '2 cut 1 2 3 4 5',
  deltas: 'deltas 1 3 6 10',
  desc: 'desc 3 1 2',
  dev: 'dev 10 343 232 55',
  differ: 'differ 1 1 2 2 3',
  distinct: 'distinct 1 2 1 3 2',
  div: '10 div 4',
  dsave: 't:([]a:1 2;b:3 4);`:/db dsave `t',
  ema: 'ema[1%3;1,3#0]',
  enlist: 'enlist 42',
  ej: 'ej[`s;([]s:`a`b;v:1 2);([]s:`a`a`c;w:10 20 30)]',
  eval: 'eval parse "1+2"',
  except: '`a`b`c except `b`d',
  exp: 'exp 0 1',
  fby: '(sum;2 5 4 1 7) fby "abbac"',
  fills: 'fills 0N 2 0N 4',
  first: 'first 10 20 30',
  fkeys: 'fkeys ([]a:1 2;b:`x`y)',
  flip: 'flip `a`b!(1 2;3 4)',
  floor: 'floor 1.2 3.9 -1.2',
  get: 'a:42;get "a"',
  getenv: 'getenv `QANVAS_REFERENCE_UNSET',
  group: 'group `a`b`a`c',
  gtime: 'gtime 2026.01.01',
  hclose: 'hclose hopen `:ref',
  hcount: 'set[`:ref;1 2 3];hcount `:ref',
  hdel: 'set[`:ref;1 2 3];hdel `:ref',
  hopen: 'hopen `:ref',
  hsym: 'hsym `ref',
  iasc: 'iasc 3 1 2',
  idesc: 'idesc 3 1 2',
  ij: '([]a:1 2;v:10 20) ij ([]a:2 3;w:200 300)',
  ijf: '([]a:1 2;v:10 20) ijf ([]a:2 3;w:200 300)',
  in: '1 2 3 in 2 3 4',
  insert: 't:([]a:1 2);`t insert 3',
  inter: '`a`b`c inter `b`d',
  inv: 'inv (1 0;0 1)',
  key: 'key `a`b!1 2',
  keys: 'keys `a`b!1 2',
  last: 'last 10 20 30',
  like: '"banana" like "b*na"',
  load: 'ref:([]a:1 2);save `:ref.csv;ref:();load `:ref.csv;ref',
  lj: '([]a:1 2;v:10 20) lj ([a:2 3]w:200 300)',
  ljf: '([]a:1 2;v:10 20) ljf ([a:2 3]w:200 300)',
  log: 'log 1 10',
  lower: 'lower "ABC"',
  lsq: '(1 2 3f;4 5 6f) lsq (1 0 0f;0 1 0f)',
  ltime: 'ltime 2026.01.01',
  ltrim: 'ltrim "  abc  "',
  max: 'max 3 1 2',
  maxs: 'maxs 3 1 4 2',
  md5: 'md5 "hello"',
  meta: 'meta ([]a:1 2;b:`x`y;c:1.5 2.5)',
  mavg: '2 mavg 1 2 3 4',
  mcount: '2 mcount 1 0N 3 4',
  mdev: '2 mdev 1 2 3 4',
  med: 'med 1 2 3 4',
  min: 'min 3 1 2',
  mins: 'mins 3 1 4 2',
  mmax: '3 mmax 5 2 7 1 4',
  mmin: '3 mmin 5 2 7 1 4',
  mmu: '(1 2;3 4) mmu (1 0;0 1)',
  mod: '10 mod 4',
  msum: '2 msum 1 2 3 4',
  neg: 'neg -3 2 1',
  next: 'next 1 2 3',
  not: 'not 1 0 1',
  null: 'null 0N 2 0N',
  or: '1 0 1 or 0 0 1',
  over: 'over[+;1 2 3]',
  parse: 'parse "1+2"',
  peach: 'neg peach 1 2 3',
  pj: '([]a:1 2;v:10 20) pj ([a:2 3]v:1 2)',
  prd: 'prd 2 3 4',
  prds: 'prds 1 2 3 4',
  prev: 'prev 1 2 3',
  prior: 'prior[-;1 3 6]',
  rank: 'rank 30 10 20',
  ratios: 'ratios 2 4 8',
  rand: 'count rand 3',
  raze: 'raze (1 2;3 4)',
  read0: 'set[`:ref.txt;"a\nb"];read0 `:ref.txt',
  read1: 'set[`:ref.txt;"ab"];read1 `:ref.txt',
  reciprocal: 'reciprocal 2 4',
  reval: 'reval parse "2+3"',
  reverse: 'reverse 1 2 3',
  rload: 't:([]a:1 2;b:3 4);rsave `t;t:();rload `t;t',
  rotate: '2 rotate 1 2 3 4',
  rsave: 't:([]a:1 2;b:3 4);rsave `t',
  rtrim: 'rtrim "abc  "',
  save: 'ref:([]a:1 2);save `:ref.csv',
  scan: 'scan[+;1 2 3]',
  scov: '2 3 5 7 scov 3 3 5 9',
  sdev: 'sdev 10 343 232 55',
  set: 'set[`a;42]',
  setenv: 'setenv[`QANVAS_REFERENCE;"ok"]',
  show: 'show 42',
  signum: 'signum -3 0 5',
  sin: 'sin 0 1',
  sqrt: 'sqrt 9 2',
  ss: '"hello world" ss "o"',
  ssr: 'ssr["hello";"l";"L"]',
  string: 'string `v2',
  sublist: '1 2 sublist 10 20 30 40',
  sum: 'sum 1 2 3',
  sums: 'sums 1 2 3 4',
  sv: '"/" sv ("usr";"local";"bin")',
  svar: 'svar 10 343 232 55',
  system: 'system "pwd"',
  tables: 't:([]a:1 2);tables `.',
  tan: 'tan 0 1',
  til: 'til 5',
  trim: 'trim "  abc  "',
  type: 'type 0Nd',
  ungroup: 'ungroup ([]s:`a`b;p:(enlist 2;5 7);q:10 20;r:(enlist "A";"BC"))',
  union: '`a`b`c union `b`d',
  upper: 'upper "abC"',
  uj: '([]a:1 2) uj ([]a:2 3)',
  ujf: '([]a:1 2) ujf ([]a:2 3)',
  upsert: 't:([]a:1 2);`t upsert 3',
  value: 'value "1+2"',
  var: 'var 1 2 3',
  view: 'a:5;v::2+a*3;view `v',
  views: 'views[]',
  vs: '"/" vs "usr/local/bin"',
  wavg: '100 50 25 wavg 10 12 20f',
  where: 'where 10110b',
  within: '1 2 3 within 2 3',
  wsum: '100 50 25 wsum 10 12 20f',
  wj: 't:([]s:`a`a;t:1 2;p:10 20);q:([]s:`a;t:2);wj[-1 0+\:q`t;`s`t;q;(t;(sum;`p))]',
  wj1: 't:([]s:`a`a;t:1 2;p:10 20);q:([]s:`a;t:2);wj1[-1 0+\:q`t;`s`t;q;(t;(sum;`p))]',
  xasc: '`a xasc ([]a:3 1 2;b:10 20 30)',
  xbar: '5 xbar 0 4 5 9 10 17',
  xcol: '`b xcol ([]a:1 2)',
  xcols: '`a`b xcols ([]a:1 2;b:3 4;c:5 6)',
  xdesc: '`a xdesc ([]a:3 1 2;b:10 20 30)',
  xexp: '2 xexp 8',
  xgroup: '`a xgroup ([]a:1 1 2;b:10 20 30)',
  xkey: '`a xkey ([]a:1 2;b:3 4)',
  xlog: '10 xlog 100',
  xprev: '2 xprev 2 7 5 3 11',
  xrank: '3 xrank 1 37 5 4 0 3'
};

const tests = [
  ['comments', '2+2  /I know this one', 'Trailing q comments do not eat the expression.'],
  ['each-prior glyph', "-':[10 15 27 93]", 'Glyph form of deltas works in the canvas/editor path.'],
  ['seeded each-prior', "-':[10;15 27 93]", 'Seeded each-prior subtracts the seed from the first item.'],
  ['while control', 'x:0;while[x<5;x+:1];x', 'Control construct loops until its condition is false.'],
  ['do control', 'y:0;do[4;y+:3];y', 'Control construct repeats its body a fixed number of times.'],
  ['if control', 'z:0;if[1;z:7];z', 'Control construct evaluates its body only when the condition is true.'],
  ['zero mavg', '0 mavg 10 20 30', 'Non-positive moving average returns float nulls.'],
  ['zero msum', '0 msum 10 20 30', 'Non-positive moving sum returns zeros.'],
  ['zero mcount', '0 mcount 10 0N 30', 'Non-positive moving count returns integer zeros.'],
  ['zero mmin', '0 mmin 10 20 30', 'Non-positive moving min preserves the source.'],
  ['negative mdev', '-2 mdev 10 20 30', 'Negative moving deviation returns float nulls.'],
  ['qsql aggregate', 'select sum v by a from ([]a:1 1 2;v:10 20 30)', 'Grouped qSQL aggregate keeps keyed-table shape.'],
  ['weighted qsql', 'select size wavg price by sym from ([]sym:`a`a`b;price:10 12 20f;size:100 50 25)', 'Weighted average works as a grouped qSQL aggregate.'],
  ['csv constant', 'csv', 'CSV delimiter keyword evaluates to a comma character.'],
  ['date null', 'null 0Nd', 'Date null parses and reports as null.'],
  ['long boundary', '2147483646i+2i', 'Integer overflow promotes with q-style display.']
] as const;

function builtinNames() {
  const builtins = listBuiltins();
  return [...new Set([...builtins.monads, ...builtins.diads, ...builtins.triads, ...builtins.quads])].sort();
}

function run(source: string) {
  const session = createSession();
  return formatValue(session.evaluate(source).value);
}

export const REFERENCE_ROWS: ReferenceRow[] = [
  ...builtinNames().map((name) => {
    const expression = primitiveSamples[name] ?? name;
    let expected = '';
    try {
      expected = run(expression);
    } catch (error) {
      expected = `error: ${(error as Error).message}\n`;
    }
    return {
      id: `primitive:${name}`,
      kind: 'primitive' as const,
      name,
      expression,
      expected,
      description: descriptions[name] ?? 'Primitive registered by q-engine; run it to inspect current support.',
      group: expression === name ? 'Primitive catalog' : 'Runnable primitive'
    };
  }),
  ...tests.map(([name, expression, description]) => ({
    id: `test:${name}`,
    kind: 'test' as const,
    name,
    expression,
    expected: run(expression),
    description,
    group: 'Parity regression'
  }))
].sort((a, b) => a.kind.localeCompare(b.kind) || a.name.localeCompare(b.name));

export function runReferenceRow(row: ReferenceRow) {
  try {
    const actual = run(row.expression);
    return {
      status: actual === row.expected ? 'pass' : 'fail',
      actual
    } as const;
  } catch (error) {
    const actual = `error: ${(error as Error).message}\n`;
    return {
      status: actual === row.expected ? 'pass' : 'error',
      actual
    } as const;
  }
}
