import "../test/dom-shims";
import { readFileSync } from "node:fs";
import { mockCtx } from "../test/helpers";
import { runHeadless } from "../src/qanvas/headless";
const code = readFileSync(process.argv[2], "utf8");
const { ctx, calls } = mockCtx();
const r = runHeadless(code, { ctx, frames: 2 });
console.log("error:", r.error?.qname, r.error?.hint);
console.log("counts:", r.counts);
console.log(calls.slice(0, 30).join("\n"));
